-- Bảng MONAN
INSERT INTO MONAN VALUES ('MN001', 'Phin Sữa Đá', 'Cà Phê Pha Phin', 35000, NULL, 'Cà phê phin pha với sữa đặc');
INSERT INTO MONAN VALUES ('MN002', 'Phin Đen Đá', 'Cà Phê Pha Phin', 29000, NULL, 'Cà phê phin đen đá truyền thống');
INSERT INTO MONAN VALUES ('MN003', 'Bạc Xỉu Đá', 'Cà Phê Pha Phin', 35000, NULL, 'Cà phê sữa pha nhạt kiểu miền Nam');

INSERT INTO MONAN VALUES ('MN004', 'Phindi Kem Sữa', 'PHINDI', 45000, NULL, 'Cà phê đậm đặc với kem sữa');
INSERT INTO MONAN VALUES ('MN005', 'Phindi Hạnh Nhân', 'PHINDI', 49000, NULL, 'Cà phê với hương vị hạnh nhân');
INSERT INTO MONAN VALUES ('MN006', 'Phindi Choco', 'PHINDI', 49000, NULL, 'Cà phê kết hợp sô-cô-la');

INSERT INTO MONAN VALUES ('MN007', 'Espresso', 'Cà Phê Espresso', 35000, NULL, 'Cà phê espresso nguyên chất');
INSERT INTO MONAN VALUES ('MN008', 'Americano', 'Cà Phê Espresso', 39000, NULL, 'Cà phê espresso pha loãng với nước nóng');
INSERT INTO MONAN VALUES ('MN009', 'Cappuccino', 'Cà Phê Espresso', 65000, NULL, 'Cà phê espresso pha với sữa và bọt sữa');
INSERT INTO MONAN VALUES ('MN010', 'Latte', 'Cà Phê Espresso', 65000, NULL, 'Cà phê pha với nhiều sữa nóng');
INSERT INTO MONAN VALUES ('MN011', 'Mocha', 'Cà Phê Espresso', 69000, NULL, 'Cà phê espresso kết hợp sô-cô-la');
INSERT INTO MONAN VALUES ('MN012', 'Caramel Macchiato', 'Cà Phê Espresso', 69000, NULL, 'Cà phê espresso với caramel và sữa');

INSERT INTO MONAN VALUES ('MN013', 'Croissant Bơ', 'Bánh Ngọt', 35000, NULL, 'Bánh croissant thơm bơ, giòn rụm lớp vỏ ngoài');
INSERT INTO MONAN VALUES ('MN014', 'Brownie Hạt Óc Chó', 'Bánh Ngọt', 45000, NULL, 'Bánh brownie đậm vị chocolate, thêm hạt óc chó bùi thơm');
INSERT INTO MONAN VALUES ('MN015', 'Mille Crepe Trà Xanh', 'Bánh Ngọt', 45000, NULL, 'Bánh nghìn lớp vị trà xanh, béo nhẹ, thơm mát và tinh tế');
INSERT INTO MONAN VALUES ('MN016', 'Mochi Kem Dâu', 'Bánh Ngọt', 42000, NULL, 'Mochi vỏ nếp dẻo, nhân kem dâu mát lạnh, ngọt dịu');

INSERT INTO MONAN VALUES ('MN017', 'Trà Sen Vàng', 'Trà', 49000, NULL, 'Trà sen vàng thanh mát, thêm sen bùi');
INSERT INTO MONAN VALUES ('MN018', 'Trà Thạch Đào', 'Trà', 49000, NULL, 'Trà đào kết hợp thạch giòn ngon');
INSERT INTO MONAN VALUES ('MN019', 'Trà Dâu Tây Kem Cheese', 'Trà', 55000, NULL, 'Trà dâu tươi mát, phủ lớp kem cheese mặn ngọt hấp dẫn');
INSERT INTO MONAN VALUES ('MN020', 'Trà Thạch Vải', 'Trà', 49000, NULL, 'Trà kết hợp thạch và vải ngọt');
INSERT INTO MONAN VALUES ('MN021', 'Matcha Đậu Đỏ', 'Trà', 49000, NULL, 'Trà xanh phối với đậu đỏ thanh mát');

INSERT INTO MONAN VALUES ('MN022', 'Freeze Trà Xanh', 'Freeze', 59000, NULL, 'Đá xay vị trà xanh truyền thống');
INSERT INTO MONAN VALUES ('MN023', 'Freeze Sô-cô-la', 'Freeze', 59000, NULL, 'Đá xay vị sô-cô-la thơm béo');
INSERT INTO MONAN VALUES ('MN024', 'Cookies và Cream Freeze', 'Freeze', 59000, NULL, 'Đá xay bánh quy và kem');
INSERT INTO MONAN VALUES ('MN025', 'Caramel Phin Freeze', 'Freeze', 65000, NULL, 'Freeze cà phê phin caramel');
INSERT INTO MONAN VALUES ('MN026', 'Classic Phin Freeze', 'Freeze', 65000, NULL, 'Freeze cà phê phin cổ điển');

INSERT INTO MONAN VALUES ('MN027', 'Tiramisu', 'Bánh ngọt', 39000, NULL, 'Bánh tiramisu mềm mịn');
INSERT INTO MONAN VALUES ('MN028', 'Mousse Dâu', 'Bánh ngọt', 39000, NULL, 'Bánh mousse dâu tươi mát lạnh');

INSERT INTO MONAN VALUES ('MN029', 'Soda Xoài Nhiệt Đới', 'Thức Uống Khác', 55000, NULL, 'Soda xoài kết hợp syrup nhiệt đới, màu đẹp, vị chua ngọt mát lạnh');
INSERT INTO MONAN VALUES ('MN030', 'Soda Việt Quất', 'Thức Uống Khác', 55000, NULL, 'Soda chua ngọt kết hợp vị việt quất độc đáo và tươi mới');
commit;

--Bảng Tài khoản - Nhân viên 
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('nguyenvanan@park.com', 'nguyenvanan123', 'Manager');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('tranthibich@park.com', 'tranthibich123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('leminhtri@park.com', 'leminhtri123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('phamquanghuy@park.com', 'phamquanghuy123', 'Employee', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('dothoailinh@park.com', 'dothoailinh123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('ngothanhlam@park.com', 'ngothanhlam123', 'Employee', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('buiduyanh@park.com', 'buiduyanh123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('hoangyennhi@park.com', 'hoangyennhi123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('danghieuthanh@park.com', 'danghieuthanh123', 'Employee');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('vuquynhanh@park.com', 'vuquynhanh123', 'Employee', 'Inactive');

commit;

-- Bảng Tài khoản - Khách hàng 
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('nguyenthithao@park.com', 'nguyenthithao123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('phamvandat@park.com', 'phamvandat123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('tranminhha@park.com', 'tranminhha123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('lethikimanh@park.com', 'lethikimanh123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('ngocminhtuan@park.com', 'ngocminhtuan123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('buihoangyen@park.com', 'buihoangyen123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('dinhngocson@park.com', 'dinhngocson123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('nguyenquynhchi@park.com', 'nguyenquynhchi123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('doanthanhtam@park.com', 'doanthanhtam123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('phamhoangloc@park.com', 'phamhoangloc123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('lethimai@park.com', 'lethimai123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('votranbao@park.com', 'votranbao123', 'Customer', 'Inactive');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('nguyenvannam@park.com', 'nguyenvannam123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK) VALUES ('hoangminhtrang@park.com', 'hoangminhtrang123', 'Customer');
INSERT INTO TAIKHOAN (EMAIL, MATKHAU, LOAITK, TRANGTHAI) VALUES ('tranthanhdat@park.com', 'tranthanhdat123', 'Customer', 'Inactive');

commit;

-- Bảng KHACHHANG
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Nguyễn Thị Thảo', TO_DATE('1992-04-15','YYYY-MM-DD'), '0901234561', 120, 'Silver', 'TK011');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Phạm Văn Đạt', TO_DATE('2005-08-22','YYYY-MM-DD'), '0901234562', 0, 'Bronze', 'TK012');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Trần Minh Hà', TO_DATE('1998-12-05','YYYY-MM-DD'), '0901234563', 310.0, 'Gold', 'TK013');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Lê Thị Kim Anh', TO_DATE('1991-06-19','YYYY-MM-DD'), '0901234564', 40.0, 'Bronze', 'TK014');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Ngọc Minh Tuấn', TO_DATE('1989-03-11','YYYY-MM-DD'), '0901234565', 180.0, 'Silver', 'TK015');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Bùi Hoàng Yến', TO_DATE('1995-10-30','YYYY-MM-DD'), '0901234566', 90.0, 'Bronze', 'TK016');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Đinh Ngọc Sơn', TO_DATE('2003-01-21','YYYY-MM-DD'), '0901234567', 0.0, 'Bronze', 'TK017');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Nguyễn Quỳnh Chi', TO_DATE('1996-09-14','YYYY-MM-DD'), '0901234568', 200, 'Gold', 'TK018');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Đoàn Thanh Tâm', TO_DATE('1993-07-09','YYYY-MM-DD'), '0901234569', 70.0, 'Bronze', 'TK019');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Phạm Hoàng Lộc', TO_DATE('2007-02-26','YYYY-MM-DD'), '0901234570', 320.0, 'Platinum', 'TK020');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Lê Thị Mai', TO_DATE('1990-11-17','YYYY-MM-DD'), '0901234571', 130.0, 'Silver', 'TK021');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Võ Trần Bảo', TO_DATE('2006-05-03','YYYY-MM-DD'), '0901234572', 0.0, 'Bronze', 'TK022');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Nguyễn Văn Nam', TO_DATE('1994-01-25','YYYY-MM-DD'), '0901234573', 200.0, 'Gold', 'TK023');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Hoàng Minh Trang', TO_DATE('1997-08-08','YYYY-MM-DD'), '0901234574', 60.0, 'Bronze', 'TK024');
INSERT INTO KHACHHANG (HOTEN, NGAYSINH, SDT, DIEMTICHLUY, LOAITV, MATK) VALUES ('Trần Thành Đạt', TO_DATE('1991-03-15','YYYY-MM-DD'), '0901234575', 400.0, 'Platinum', 'TK025');


--Bảng Nhân viên
-- 1. Quản lý
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Nguyễn Văn An', TO_DATE('1995-06-12', 'YYYY-MM-DD'), '0901234567', TO_DATE('2023-01-10', 'YYYY-MM-DD'), 'Quản lý', 18000000, NULL, 'TK001');

-- 2. Thu ngân
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Trần Thị Bích', TO_DATE('1998-04-22', 'YYYY-MM-DD'), '0912345678', TO_DATE('2023-06-15', 'YYYY-MM-DD'), 'Thu ngân', 9000000, 'NV001', 'TK002');

-- 3. Pha chế
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Lê Minh Trí', TO_DATE('2000-11-01', 'YYYY-MM-DD'), '0908765432', TO_DATE('2024-02-20', 'YYYY-MM-DD'), 'Pha chế', 9500000, 'NV001', 'TK003');

-- 4. Phục vụ (Inactive)
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Phạm Quang Huy', TO_DATE('1999-07-10', 'YYYY-MM-DD'), '0934567890', TO_DATE('2023-10-05', 'YYYY-MM-DD'), 'Phục vụ', 8500000, 'NV001', 'TK004');

-- 5. Pha chế
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Đỗ Hoài Linh', TO_DATE('2001-03-28', 'YYYY-MM-DD'), '0945678901', TO_DATE('2024-03-30', 'YYYY-MM-DD'), 'Pha chế', 9500000, 'NV001', 'TK005');

-- 6. Phục vụ (Inactive)
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Ngô Thành Lâm', TO_DATE('2002-09-05', 'YYYY-MM-DD'), '0961234567', TO_DATE('2023-09-12', 'YYYY-MM-DD'), 'Phục vụ', 8500000, 'NV001', 'TK006');

-- 7. Thu ngân
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Bùi Duy Anh', TO_DATE('1997-12-09', 'YYYY-MM-DD'), '0977654321', TO_DATE('2024-07-08', 'YYYY-MM-DD'), 'Thu ngân', 9000000, 'NV001', 'TK007');

-- 8. Tạp vụ
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Hoàng Yến Nhi', TO_DATE('2003-01-14', 'YYYY-MM-DD'), '0986543210', TO_DATE('2024-08-25', 'YYYY-MM-DD'), 'Tạp vụ', 7800000, 'NV001', 'TK008');

-- 9. Bảo vệ
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Đặng Hiếu Thành', TO_DATE('1996-10-30', 'YYYY-MM-DD'), '0918765432', TO_DATE('2025-01-05', 'YYYY-MM-DD'), 'Bảo vệ', 8000000, 'NV001', 'TK009');

-- 10. Phục vụ (Inactive)
INSERT INTO NHANVIEN (HOTEN, NGAYSINH, SDT, NGAYVL, CHUCVU, LUONG, MAQL, MATK)
VALUES ('Vũ Quỳnh Anh', TO_DATE('2000-08-18', 'YYYY-MM-DD'), '0909988776', TO_DATE('2023-04-20', 'YYYY-MM-DD'), 'Phục vụ', 8500000, 'NV001', 'TK010');

commit;

-- Bảng Chấm công
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-16', 'YYYY-MM-DD'), 6, 'NV001');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-17', 'YYYY-MM-DD'), 7, 'NV002');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-18', 'YYYY-MM-DD'), 8, 'NV010');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-20', 'YYYY-MM-DD'), 6, 'NV008');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-21', 'YYYY-MM-DD'), 7, 'NV008');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-21', 'YYYY-MM-DD'), 6, 'NV010');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-22', 'YYYY-MM-DD'), 6, 'NV003');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-23', 'YYYY-MM-DD'), 6, 'NV008');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-24', 'YYYY-MM-DD'), 6, 'NV010');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-26', 'YYYY-MM-DD'), 6, 'NV001');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-26', 'YYYY-MM-DD'), 6, 'NV007');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-26', 'YYYY-MM-DD'), 8, 'NV008');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-27', 'YYYY-MM-DD'), 6, 'NV008');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-27', 'YYYY-MM-DD'), 6, 'NV009');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-28', 'YYYY-MM-DD'), 6, 'NV001');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-28', 'YYYY-MM-DD'), 6, 'NV009');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-28', 'YYYY-MM-DD'), 8, 'NV005');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-29', 'YYYY-MM-DD'), 8, 'NV006');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-29', 'YYYY-MM-DD'), 8, 'NV002');
INSERT INTO CHAMCONG (NGAYLV, SOGIOLAM, MANV) VALUES (TO_DATE('2025-05-30', 'YYYY-MM-DD'), 7, 'NV009');

commit;

-- Bảng Sản phẩm
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Cà phê hạt Arabica', 'Nguyên liệu', 50, 'kg', 'In stock', 180000, TO_DATE('2025-04-01','YYYY-MM-DD'), TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Sữa tươi không đường', 'Nguyên liệu', 30, 'lít', 'In stock', 25000, TO_DATE('2025-05-15','YYYY-MM-DD'), TO_DATE('2025-06-15','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Trà đen túi lọc', 'Nguyên liệu', 200, 'túi', 'In stock', 5000, TO_DATE('2025-03-01','YYYY-MM-DD'), TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Bột cacao nguyên chất', 'Nguyên liệu', 20, 'kg', 'In stock', 120000, TO_DATE('2025-04-10','YYYY-MM-DD'), TO_DATE('2026-04-10','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Đường trắng', 'Nguyên liệu', 100, 'kg', 'In stock', 15000, TO_DATE('2025-03-20','YYYY-MM-DD'), TO_DATE('2026-03-20','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Ly nhựa 500ml', 'Dụng cụ', 300, 'cái', 'In stock', 1200, TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2026-05-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Ống hút', 'Dụng cụ', 500, 'cái', 'In stock', 500, TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2026-05-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Syrup caramel', 'Nguyên liệu', 10, 'chai', 'In stock', 85000, TO_DATE('2025-04-05','YYYY-MM-DD'), TO_DATE('2026-04-05','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Kem xịt whipping', 'Nguyên liệu', 25, 'chai', 'In stock', 45000, TO_DATE('2025-05-01', 'YYYY-MM-DD'), TO_DATE('2025-08-01', 'YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Trà xanh matcha', 'Nguyên liệu', 15, 'kg', 'In stock', 150000, TO_DATE('2025-04-15','YYYY-MM-DD'), TO_DATE('2026-04-15','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Syrup dâu', 'Nguyên liệu', 12, 'chai', 'In stock', 75000, TO_DATE('2025-04-25','YYYY-MM-DD'), TO_DATE('2026-04-25','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Ly thủy tinh 350ml', 'Dụng cụ', 50, 'cái', 'In stock', 15000, TO_DATE('2025-03-01','YYYY-MM-DD'), TO_DATE('2026-03-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Khăn giấy', 'Dụng cụ', 200, 'bịch', 'In stock', 10000, TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2026-01-01','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Syrup bạc hà', 'Nguyên liệu', 10, 'chai', 'In stock', 82000, TO_DATE('2025-04-20','YYYY-MM-DD'), TO_DATE('2026-04-20','YYYY-MM-DD'));
INSERT INTO SANPHAM (TENSP, LOAISP, TONG_SL, DONVITINH, TRANGTHAI, GIANHAP, NGAYSX, HANSD) VALUES ('Muỗng nhựa', 'Dụng cụ', 300, 'cái', 'In stock', 300, TO_DATE('2025-05-10','YYYY-MM-DD'), TO_DATE('2026-05-10','YYYY-MM-DD'));

commit;

-- Bảng PHIEUKHO
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK001', TO_DATE('2025-05-10', 'YYYY-MM-DD'), 'NHAP', 'NV001', 'Nhập nguyên liệu đợt 1');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK002', TO_DATE('2025-05-12', 'YYYY-MM-DD'), 'NHAP', 'NV002', 'Nhập dụng cụ và vật tư');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK003', TO_DATE('2025-05-13', 'YYYY-MM-DD'), 'XUAT', 'NV003', 'Xuất nguyên liệu pha chế');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK004', TO_DATE('2025-05-14', 'YYYY-MM-DD'), 'XUAT', 'NV004', 'Xuất dụng cụ phục vụ');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK005', TO_DATE('2025-05-15', 'YYYY-MM-DD'), 'NHAP', 'NV005', 'Nhập nguyên liệu bổ sung');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK006', TO_DATE('2025-05-16', 'YYYY-MM-DD'), 'XUAT', 'NV006', 'Xuất nguyên liệu cho pha chế');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK007', TO_DATE('2025-05-17', 'YYYY-MM-DD'), 'NHAP', 'NV007', 'Nhập nguyên liệu mùa hè');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK008', TO_DATE('2025-05-18', 'YYYY-MM-DD'), 'XUAT', 'NV008', 'Xuất dụng cụ và vật tư');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK009', TO_DATE('2025-05-19', 'YYYY-MM-DD'), 'NHAP', 'NV009', 'Nhập nguyên liệu đặc biệt');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK010', TO_DATE('2025-05-20', 'YYYY-MM-DD'), 'XUAT', 'NV010', 'Xuất nguyên liệu pha chế');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK011', TO_DATE('2025-05-21', 'YYYY-MM-DD'), 'NHAP', 'NV001', 'Nhập nguyên liệu mới');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK012', TO_DATE('2025-05-22', 'YYYY-MM-DD'), 'XUAT', 'NV002', 'Xuất dụng cụ phục vụ');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK013', TO_DATE('2025-05-23', 'YYYY-MM-DD'), 'NHAP', 'NV003', 'Nhập vật tư khuyến mãi');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK014', TO_DATE('2025-05-24', 'YYYY-MM-DD'), 'XUAT', 'NV004', 'Xuất nguyên liệu pha chế');
INSERT INTO PHIEUKHO (MAPHIEU, NGAYGIAODICH, LOAIPHIEU, MANV, GHICHU) VALUES ('PK015', TO_DATE('2025-05-25', 'YYYY-MM-DD'), 'NHAP', 'NV005', 'Nhập bổ sung dụng cụ');

-- Bảng CT_PHIEUKHO
-- NHẬP NGUYÊN LIỆU ĐỢT 1
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK001', 'SP001', 20, 180000); -- Cà phê hạt Arabica
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK001', 'SP002', 10, 25000);  -- Sữa tươi không đường

-- NHẬP DỤNG CỤ & VẬT TƯ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK002', 'SP006', 100, 1200);   -- Ly nhựa 500ml
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK002', 'SP007', 200, 500);    -- Ống hút

-- XUẤT NGUYÊN LIỆU PHA CHẾ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK003', 'SP004', 5, 120000);   -- Bột cacao nguyên chất
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK003', 'SP005', 10, 15000);   -- Đường trắng

-- XUẤT DỤNG CỤ PHỤC VỤ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK004', 'SP006', 50, 1200);    -- Ly nhựa 500ml
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK004', 'SP015', 100, 300);    -- Muỗng nhựa

-- NHẬP NGUYÊN LIỆU BỔ SUNG
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK005', 'SP008', 5, 85000);    -- Syrup caramel
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK005', 'SP009', 10, 45000);   -- Kem xịt whipping

-- XUẤT NGUYÊN LIỆU CHO PHA CHẾ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK006', 'SP010', 5, 150000);   -- Trà xanh matcha
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK006', 'SP011', 3, 75000);    -- Syrup dâu

-- NHẬP NGUYÊN LIỆU MÙA HÈ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK007', 'SP014', 5, 82000);    -- Syrup bạc hà
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK007', 'SP003', 50, 5000);    -- Trà đen túi lọc

-- XUẤT DỤNG CỤ & VẬT TƯ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK008', 'SP013', 20, 15000);   -- Ly thủy tinh 350ml
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK008', 'SP015', 100, 300);    -- Muỗng nhựa

-- NHẬP NGUYÊN LIỆU ĐẶC BIỆT
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK009', 'SP012', 30, 10000);   -- Khăn giấy
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK009', 'SP002', 10, 25000);   -- Sữa tươi không đường

-- XUẤT NGUYÊN LIỆU PHA CHẾ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK010', 'SP008', 2, 85000);    -- Syrup caramel
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK010', 'SP009', 3, 45000);    -- Kem xịt whipping

-- NHẬP NGUYÊN LIỆU MỚI
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK011', 'SP010', 3, 150000);   -- Trà xanh matcha
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK011', 'SP011', 2, 75000);    -- Syrup dâu

-- XUẤT DỤNG CỤ PHỤC VỤ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK012', 'SP006', 40, 1200);    -- Ly nhựa 500ml
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK012', 'SP007', 50, 500);     -- Ống hút

-- NHẬP VẬT TƯ KHUYẾN MÃI
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK013', 'SP013', 10, 15000);   -- Ly thủy tinh 350ml
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK013', 'SP012', 20, 10000);   -- Khăn giấy

-- XUẤT NGUYÊN LIỆU PHA CHẾ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK014', 'SP001', 10, 180000);  -- Cà phê hạt Arabica
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK014', 'SP003', 20, 5000);    -- Trà đen túi lọc

-- NHẬP BỔ SUNG DỤNG CỤ
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK015', 'SP007', 100, 500);    -- Ống hút
INSERT INTO CT_PHIEUKHO (MAPHIEU, MASP, SOLUONG, DONGIA) VALUES ('PK015', 'SP015', 100, 300);    -- Muỗng nhựa

commit;

-- Bảng KHUYẾN MÃI
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM001', 'Ưu đãi khách hàng thân thiết', 'Giảm theo cố định', 50000, 'Tích điểm đủ 1000 điểm', TO_DATE('2025-01-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM002', 'Ưu đãi khách VIP', 'Giảm theo cố định', 100000, 'Khách VIP', TO_DATE('2025-01-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM003', 'Giảm giá ngày sinh nhật', 'Giảm theo %', 20, 'Xuất trình CMND ngày sinh nhật', TO_DATE('2025-01-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM004', 'Giảm giá buổi sáng', 'Giảm theo %', 20, 'Áp dụng từ 7h-10h', TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2025-06-01','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM005', 'Giảm giá khách hàng mới', 'Giảm theo %', 25, 'Áp dụng lần đầu tiên', TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2025-07-01','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM006', 'Giảm giá nhân viên', 'Giảm theo cố định', 20000, 'Dành cho nhân viên quán', TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM007', 'Ưu đãi học sinh sinh viên', 'Giảm theo %', 20, 'Xuất trình thẻ học sinh, sinh viên', TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM008', 'Giảm giá combo', 'Giảm theo cố định', 60000, 'Mua combo 3 sản phẩm', TO_DATE('2025-05-10','YYYY-MM-DD'), TO_DATE('2025-06-10','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM009', 'Khuyến mãi cuối tháng 5', 'Giảm theo cố định', 25000, 'Hóa đơn trên 100k', TO_DATE('2025-05-25','YYYY-MM-DD'), TO_DATE('2025-05-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM010', 'Giảm giá cuối tháng', 'Giảm theo cố định', 40000, 'Hóa đơn trên 200k', TO_DATE('2025-05-25','YYYY-MM-DD'), TO_DATE('2025-05-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM011', 'Ưu đãi khách mua lần 2', 'Giảm theo %', 15, 'Khách mua lần 2 trong tháng', TO_DATE('2025-05-01','YYYY-MM-DD'), TO_DATE('2025-05-31','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM012', 'Mừng Tết thiếu nhi 1/6', 'Giảm theo %', 15, 'Hóa đơn trên 150k', TO_DATE('2025-05-30','YYYY-MM-DD'), TO_DATE('2025-06-06','YYYY-MM-DD'), 'Đang áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM013', 'Mua 1 tặng 1', 'Miễn phí', 0, 'Áp dụng cho trà sữa', TO_DATE('2025-05-20','YYYY-MM-DD'), TO_DATE('2025-05-25','YYYY-MM-DD'), 'Hết hạn');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM014', 'Khuyến mãi cuối tuần', 'Giảm theo %', 10, 'Áp dụng cuối tuần', TO_DATE('2025-05-17','YYYY-MM-DD'), TO_DATE('2025-05-18','YYYY-MM-DD'), 'Hết hạn');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM015', 'Giảm giá cuối tuần', 'Giảm theo cố định', 30000, 'Hóa đơn từ 100k', TO_DATE('2025-05-15','YYYY-MM-DD'), TO_DATE('2025-05-18','YYYY-MM-DD'), 'Hết hạn');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM016', 'Ưu đãi ngày lễ', 'Giảm theo cố định', 35000, 'Áp dụng ngày lễ', TO_DATE('2025-06-01','YYYY-MM-DD'), TO_DATE('2025-06-03','YYYY-MM-DD'), 'Sắp áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM017', 'Khuyến mãi mùa hè', 'Giảm theo %', 10, 'Mua từ 2 ly trở lên', TO_DATE('2025-06-01','YYYY-MM-DD'), TO_DATE('2025-06-30','YYYY-MM-DD'), 'Sắp áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM018', 'Giảm giá theo mùa', 'Giảm theo cố định', 40000, 'Hóa đơn trên 150k', TO_DATE('2025-06-01','YYYY-MM-DD'), TO_DATE('2025-08-31','YYYY-MM-DD'), 'Sắp áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM019', 'Giảm giá cuối năm', 'Giảm theo %', 30, 'Hóa đơn trên 300k', TO_DATE('2025-12-01','YYYY-MM-DD'), TO_DATE('2025-12-31','YYYY-MM-DD'), 'Sắp áp dụng');
INSERT INTO KHUYENMAI (MAKM, TENKM, LOAIKM, GIATRIGIAM, DIEUKIEN, NGAYBD, NGAYKT, TRANGTHAI) VALUES ('KM020', 'Khuyến mãi ngày 20/11', 'Giảm theo %', 20, 'Áp dụng ngày 20/11', TO_DATE('2025-11-20','YYYY-MM-DD'), TO_DATE('2025-11-20','YYYY-MM-DD'), 'Sắp áp dụng');

commit;

