
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;

CREATE TABLE TAIKHOAN (
    MATK VARCHAR2(20) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MATKHAU VARCHAR2(50) NOT NULL,
    LOAITK VARCHAR2(20),
    TRANGTHAI VARCHAR2(20) DEFAULT 'Active'
);
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_LOAITK CHECK(LOAITK IN('Manager', 'Employee', 'Customer'));
ALTER TABLE TAIKHOAN ADD CONSTRAINT chk_TRANGTHAI CHECK(TRANGTHAI IN('Active', 'Inactive'));

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    GIOITINH VARCHAR2(10),
    SDT VARCHAR2(15) NOT NULL UNIQUE,
    DIACHI VARCHAR2(255),
    NGAYVL DATE DEFAULT SYSDATE,
    CHUCVU VARCHAR2(30),
    LUONG NUMBER(10, 2) NOT NULL,
    MAQL VARCHAR2(20),
    MATK VARCHAR2(20),
    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_GIOITINH_NV CHECK(GIOITINH IN('Male', 'Female', 'None'));
ALTER TABLE NHANVIEN ADD CONSTRAINT chk_LUONG CHECK(LUONG >= 0);

CREATE TABLE CHAMCONG (
    MACHAMCONG VARCHAR2(20) PRIMARY KEY,
    SONGAYLV NUMBER(5) NOT NULL,
    SOGIOLAM NUMBER(5, 2) NOT NULL,
    MANV VARCHAR2(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE KHACHHANG (
    MAKH VARCHAR2(20) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    NGAYSINH DATE,
    EMAIL VARCHAR2(100),
    SDT VARCHAR2(15) UNIQUE,
    DIEMTICHLUY NUMBER(10, 2) DEFAULT 0,
    LOAITV VARCHAR2(20) DEFAULT 'Bronze'
--    MATK VARCHAR2(20) UNIQUE,
--    FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);
--ALTER TABLE KHACHHANG ADD CONSTRAINT chk_GIOITINH_KH CHECK(GIOITINH IN('Male', 'Female', 'None'));
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_LOAITV CHECK(LOAITV IN('Bronze', 'Silver', 'Gold', 'Platinum'));
ALTER TABLE KHACHHANG ADD CONSTRAINT chk_NGAYSINH CHECK(DIEMTICHLUY >= 0);

CREATE TABLE MONAN (
    MAMON VARCHAR2(20) PRIMARY KEY,
    TENMON VARCHAR2(100) NOT NULL UNIQUE,
    DANHMUC VARCHAR2(50),
    GIABAN NUMBER(10, 2),
    HINHANH VARCHAR2(255),
    MOTA VARCHAR2(255)
);
ALTER TABLE MONAN ADD CONSTRAINT chk_GIABAN CHECK(GIABAN >= 0);

--CREATE TABLE COMBO_MON (
--    MACB VARCHAR2(20) PRIMARY KEY,
--    TENCB VARCHAR2(100) NOT NULL UNIQUE,
--    LOAICB VARCHAR2(50),
--    GIACB NUMBER(10, 2),
--    HINHANH VARCHAR2(255),
--    TRANGTHAI VARCHAR2(20) DEFAULT 'Available',
--    MOTA VARCHAR2(255)
--);
--ALTER TABLE COMBO_MON ADD CONSTRAINT chk_GIACB CHECK(GIACB >= 0);
--ALTER TABLE COMBO_MON ADD CONSTRAINT chk_TRANGTHAI CHECK(TRANGTHAI IN('Available', 'Sold out'));
--
--CREATE TABLE CHITIET_COMBO (
--    MACB VARCHAR2(20),
--    MAMON VARCHAR2(20),
--    SOLUONG NUMBER(5),
--    PRIMARY KEY (MACB, MAMON),
--    FOREIGN KEY (MACB) REFERENCES COMBO_MON(MACB),
--    FOREIGN KEY (MAMON) REFERENCES MENU(MAMON)
--);
--ALTER TABLE CHITIET_COMBO ADD CONSTRAINT chk_SOLUONG CHECK(SOLUONG > 0);

CREATE TABLE SANPHAM (
    MASP VARCHAR2(20) PRIMARY KEY,
    TENSP VARCHAR2(100) NOT NULL,
    LOAISP VARCHAR2(50),
    TONG_SL NUMBER(10) DEFAULT 0,
    DONVITINH VARCHAR2(20) NOT NULL,
    TRANGTHAI VARCHAR2(20) DEFAULT 'In stock',
    GIANHAP NUMBER(10, 2),
    NGAYSX DATE,
    HANSD DATE
);
ALTER TABLE SANPHAM ADD CONSTRAINT chk_SOLUONG_SP CHECK(TONGSL >= 0);
ALTER TABLE SANPHAM ADD CONSTRAINT chk_GIANHAP CHECK(GIANHAP >= 0);
ALTER TABLE SANPHAM ADD CONSTRAINT chk_TRANGTHAI_SP CHECK(TRANGTHAI IN('In stock', 'Out of stock'));

CREATE TABLE CHITIET_SP (
    NGAY DATE DEFAULT SYSDATE,
    SL NUMBER(10) NOT NULL,
    LOAIGD VARCHAR2(10),
    MASP VARCHAR2(20),
    MANV VARCHAR2(20),
    FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
ALTER TABLE CHITIET_SP ADD CONSTRAINT chk_SOLUONG_CTSP CHECK(SL >= 0);
ALTER TABLE CHITIET_SP ADD CONSTRAINT chk_LOAIGD CHECK (LOAIGD IN ('NHAP', 'XUAT'));


CREATE TABLE HOADON (
    MAHD VARCHAR2(20) PRIMARY KEY,
    TONGTIENTRUOC NUMBER(10, 2),
    TIENGIAMGIA NUMBER(10, 2),
    TONGTIENSAU NUMBER(10, 2),
    HINHTHUCTT VARCHAR2(50),
    NGAYLAP DATE DEFAULT SYSDATE,
    GHICHU VARCHAR2(255),
    MAKH VARCHAR2(20),
    MANV VARCHAR2(20),
    MAKM VARCHAR2(20),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKM) REFERENCES KHUYENMAI(MAKM)
);

CREATE TABLE CHITIET_HD (
    MAHD VARCHAR2(20),
    LOAI VARCHAR2(20),
    MALOAI VARCHAR2(20),
    DONGIA NUMBER(10, 2),
    SOLUONG NUMBER(5) NOT NULL,
    THANHTIEN NUMBER(10, 2),
    PRIMARY KEY (MAHD, LOAI, MALOAI),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);
ALTER TABLE CHITIET_HD ADD CONSTRAINT chk_SOLUONG CHECK(SOLUONG > 0);

CREATE TABLE KHUYENMAI (
    MAKM VARCHAR2(20) PRIMARY KEY,
    TENKM VARCHAR2(100) NOT NULL,
    LOAIKM VARCHAR2(50) NOT NULL,
    GIATRIGIAM NUMBER(10, 2),
    DIEUKIEN VARCHAR2(255),
    NGAYBD DATE DEFAULT SYSDATE,
    NGAYKT DATE DEFAULT SYSDATE,
    TRANGTHAI VARCHAR2(20)
);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_GIATRIGIAM CHECK(GIATRIGIAM > 0);
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_TRANGTHAI_KM CHECK(TRANGTHAI IN('Available', 'Unavailable'));
ALTER TABLE KHUYENMAI ADD CONSTRAINT chk_NGAY CHECK(NGAYKT >= NGAYBD);

--CREATE TABLE LICHSU_DIEM (
--    MALS VARCHAR2(20) PRIMARY KEY,
--    MAKH VARCHAR2(20),
--    NGAY DATE DEFAULT SYSDATE,
--    DIEMTICHLUY NUMBER(10, 2),
--    GHICHU VARCHAR2(255),
--    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
--);
--ALTER TABLE LICHSU_DIEM ADD CONSTRAINT chk_DIEMTICHLUY CHECK(DIEMTICHLUY >= 0);

