-- Bảng Tài khoản
CREATE SEQUENCE seq_taikhoan
START WITH 1
INCREMENT BY 1
NOCACHE
ORDER
NOCYCLE;

CREATE OR REPLACE TRIGGER trg_taikhoan_pk
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    SELECT 'TK' || LPAD(seq_taikhoan.NEXTVAL, 3, '0') INTO :NEW.MATK FROM dual;
END;

-- Bảng Khách hàng 
CREATE SEQUENCE seq_khachhang START WITH 1 INCREMENT BY 1 NOCACHE ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER trg_khachhang_pk
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    SELECT 'KH' || LPAD(seq_khachhang.NEXTVAL, 3, '0') INTO :NEW.MAKH FROM dual;
END;

-- Bảng Nhân viên
CREATE SEQUENCE seq_nhanvien START WITH 1 INCREMENT BY 1 NOCACHE ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER trg_nhanvien_pk
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    SELECT 'NV' || LPAD(seq_nhanvien.NEXTVAL, 3, '0') INTO :NEW.MANV FROM dual;
END;

-- Bảng Chấm công
CREATE SEQUENCE seq_chamcong START WITH 1 INCREMENT BY 1 NOCACHE ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER trg_chamcong_pk
BEFORE INSERT ON CHAMCONG
FOR EACH ROW
BEGIN
    SELECT 'CC' || LPAD(seq_chamcong.NEXTVAL, 3, '0') INTO :NEW.MACHAMCONG FROM dual;
END;

-- Bảng hóa đơn
CREATE SEQUENCE seq_hoadon START WITH 1 INCREMENT BY 1 NOCACHE ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER trg_hoadon_pk
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    SELECT 'HD' || LPAD(seq_hoadon.NEXTVAL, 3, '0') INTO :NEW.MAHD FROM dual;
END;


CREATE OR REPLACE TRIGGER trg_cong_diem_tich_luy
AFTER INSERT ON HOADON
FOR EACH ROW
DECLARE
    v_diem_cong NUMBER(10, 0);
BEGIN
    -- Tính điểm: 1 điểm cho mỗi 1.000 đồng (làm tròn xuống)
    v_diem_cong := FLOOR(:NEW.TONGTIENSAU / 1000);

    UPDATE KHACHHANG
    SET DIEMTICHLUY = NVL(DIEMTICHLUY, 0) + v_diem_cong
    WHERE MAKH = :NEW.MAKH;
END;


-- Bảng Sản phẩm 
CREATE SEQUENCE seq_sanpham START WITH 1 INCREMENT BY 1 NOCACHE ORDER NOCYCLE;

CREATE OR REPLACE TRIGGER trg_sanpham_pk
BEFORE INSERT ON SANPHAM
FOR EACH ROW
BEGIN
    SELECT 'SP' || LPAD(seq_sanpham.NEXTVAL, 3, '0') INTO :NEW.MASP FROM dual;
END;

-- Bảng CHITIET_PHIEUKHO 
CREATE OR REPLACE TRIGGER trg_capnhat_tongsl
AFTER INSERT OR UPDATE OR DELETE ON CT_PHIEUKHO
FOR EACH ROW
DECLARE
    v_loaiphieu PHIEUKHO.LOAIPHIEU%TYPE;
BEGIN
    IF INSERTING OR UPDATING THEN
        SELECT LOAIPHIEU INTO v_loaiphieu FROM PHIEUKHO WHERE MAPHIEU = :NEW.MAPHIEU;

        IF v_loaiphieu = 'NHAP' THEN

            IF INSERTING THEN
                UPDATE SANPHAM
                SET TONG_SL = TONG_SL + :NEW.SOLUONG
                WHERE MASP = :NEW.MASP;
            ELSIF UPDATING THEN
                UPDATE SANPHAM
                SET TONG_SL = TONG_SL - :OLD.SOLUONG + :NEW.SOLUONG
                WHERE MASP = :NEW.MASP;
            END IF;
        ELSIF v_loaiphieu = 'XUAT' THEN

            IF INSERTING THEN
                UPDATE SANPHAM
                SET TONG_SL = TONG_SL - :NEW.SOLUONG
                WHERE MASP = :NEW.MASP;
            ELSIF UPDATING THEN
                UPDATE SANPHAM
                SET TONG_SL = TONG_SL + :OLD.SOLUONG - :NEW.SOLUONG
                WHERE MASP = :NEW.MASP;
            END IF;
        END IF;
    ELSIF DELETING THEN
        SELECT LOAIPHIEU INTO v_loaiphieu FROM PHIEUKHO WHERE MAPHIEU = :OLD.MAPHIEU;

        IF v_loaiphieu = 'NHAP' THEN
            UPDATE SANPHAM
            SET TONG_SL = TONG_SL - :OLD.SOLUONG
            WHERE MASP = :OLD.MASP;
        ELSIF v_loaiphieu = 'XUAT' THEN
            UPDATE SANPHAM
            SET TONG_SL = TONG_SL + :OLD.SOLUONG
            WHERE MASP = :OLD.MASP;
        END IF;
    END IF;
END;

-- Trigger kiểm tra đủ hàng tồn trước khi xuất kho
CREATE OR REPLACE TRIGGER trg_kiemtra_xuat
BEFORE INSERT ON CT_PHIEUKHO
FOR EACH ROW
DECLARE
    v_loaiphieu PHIEUKHO.LOAIPHIEU%TYPE;
    v_tongsl NUMBER;
BEGIN
    SELECT LOAIPHIEU INTO v_loaiphieu FROM PHIEUKHO WHERE MAPHIEU = :NEW.MAPHIEU;

    IF v_loaiphieu = 'XUAT' THEN
        SELECT TONG_SL INTO v_tongsl FROM SANPHAM WHERE MASP = :NEW.MASP;

        IF v_tongsl < :NEW.SOLUONG THEN
            RAISE_APPLICATION_ERROR(-20001, 'Không đủ hàng trong kho để xuất.');
        END IF;
    END IF;
END;

commit;

-- Bảng khách hàng
CREATE OR REPLACE TRIGGER trg_set_loaitv
BEFORE INSERT OR UPDATE ON KHACHHANG
FOR EACH ROW
BEGIN
    IF :NEW.DIEMTICHLUY <= 500 THEN
        :NEW.LOAITV := 'Bronze';
    ELSIF :NEW.DIEMTICHLUY <= 1000 THEN
        :NEW.LOAITV := 'Silver';
    ELSIF :NEW.DIEMTICHLUY <= 2999 THEN
        :NEW.LOAITV := 'Gold';
    ELSE
        :NEW.LOAITV := 'Platinum';
    END IF;
END;

