-- Bảng Tài khoản
CREATE SEQUENCE seq_taikhoan START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_taikhoan_pk
BEFORE INSERT ON TAIKHOAN
FOR EACH ROW
BEGIN
    SELECT seq_taikhoan.NEXTVAL INTO :NEW.MATK FROM dual;
END;

-- Bảng Khách hàng 
CREATE SEQUENCE seq_khachhang START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_khachhang_pk
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    SELECT seq_khachhang.NEXTVAL INTO :NEW.MAKH FROM dual;
END;

-- Bảng Nhân viên
CREATE SEQUENCE seq_nhanvien START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_nhanvien_pk
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    SELECT seq_nhanvien.NEXTVAL INTO :NEW.MANV FROM dual;
END;

-- Bảng hóa đơn
CREATE SEQUENCE seq_hoadon START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_hoadon_pk
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    SELECT 'HD' || LPAD(seq_hoadon.NEXTVAL, 3, '0') INTO :NEW.MAHD FROM dual;
END;

-- Bảng CHITIET_SP
CREATE OR REPLACE TRIGGER trg_capnhat_tongsl
AFTER INSERT ON CHITIET_SP
FOR EACH ROW
BEGIN
    IF :NEW.LOAIGD = 'NHAP' THEN
        UPDATE SANPHAM
        SET TONG_SL = TONG_SL + :NEW.SL
        WHERE MASP = :NEW.MASP;
    ELSIF :NEW.LOAIGD = 'XUAT' THEN
        UPDATE SANPHAM
        SET TONG_SL = TONG_SL - :NEW.SL
        WHERE MASP = :NEW.MASP;
    END IF;
END;


CREATE OR REPLACE TRIGGER trg_kiemtra_xuat
BEFORE INSERT ON CHITIET_SP
FOR EACH ROW
WHEN (NEW.LOAIGD = 'XUAT')
DECLARE
    v_tongsl NUMBER;
BEGIN
    SELECT TONG_SL INTO v_tongsl
    FROM SANPHAM
    WHERE MASP = :NEW.MASP;

    IF v_tongsl < :NEW.SL THEN
        RAISE_APPLICATION_ERROR(-20001, 'Không đủ hàng trong kho để xuất.');
    END IF;
END;


