
package View;

import dao.KhuyenMaiDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.KhuyenMai;

/**
 *
 * @author nttma
 */
public class C_dealPanel extends javax.swing.JPanel {

    private DefaultTableModel voucherModel;
    private KhuyenMaiDAO khuyenMaiDAO = new KhuyenMaiDAO();
    /**
     * Creates new form C_dealPanel
     */
    public C_dealPanel() {
        initComponents();
        
        initVoucherTable();
    }
    
    private void initVoucherTable() {
        voucherModel = new DefaultTableModel(new String[]{"Mã KM", "Tên KM", "Loại KM", "Giá trị giảm", "Điều kiện", "Ngày BD", "Ngày KT"}, 0);
        voucherTable.setModel(voucherModel);
        loadVoucherData();
    }

    private void loadVoucherData() {
        voucherModel.setRowCount(0);
        List<KhuyenMai> list = khuyenMaiDAO.getKhuyenMaiDangApDung();
        for (KhuyenMai km : list) {
            voucherModel.addRow(new Object[]{
                km.getMaKM(), km.getTenKM(), km.getLoaiKM(), km.getGiaTriGiam(),
                km.getDieuKien(), km.getNgayBD(), km.getNgayKT()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        codeScrollPane = new javax.swing.JScrollPane();
        codePanel = new javax.swing.JPanel();
        voucherScrollPane = new javax.swing.JScrollPane();
        voucherTable = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(252, 252, 246));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(245, 245, 220));

        menuLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("discount code");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setText("name");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        welcomeLabel.setText("Welcome,");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeLabel)
                    .addComponent(nameLabel))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        codePanel.setBackground(new java.awt.Color(252, 252, 246));

        voucherTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        voucherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Discount Value", "Condition", "Start Date", "End Date"
            }
        ));
        voucherTable.setRowHeight(30);
        voucherScrollPane.setViewportView(voucherTable);

        javax.swing.GroupLayout codePanelLayout = new javax.swing.GroupLayout(codePanel);
        codePanel.setLayout(codePanelLayout);
        codePanelLayout.setHorizontalGroup(
            codePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(voucherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        codePanelLayout.setVerticalGroup(
            codePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(voucherScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        codeScrollPane.setViewportView(codePanel);

        jPanel1.add(codeScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel codePanel;
    private javax.swing.JScrollPane codeScrollPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JScrollPane voucherScrollPane;
    private javax.swing.JTable voucherTable;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
