
package View;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author nttma
 */
public class C_ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form C_ForgotPassword
     */
    public C_ForgotPassword() {
        initComponents();
        
        showCheckBox.setContentAreaFilled(false);
        showCheckBox.setBorderPainted(false);
        showCheckBox.setFocusPainted(false);
        
        showCheckBox1.setContentAreaFilled(false);
        showCheckBox1.setBorderPainted(false);
        showCheckBox1.setFocusPainted(false);
        
        newPasswordField.setEchoChar((char)0);
        newPasswordField1.setEchoChar((char)0);   
        
        signinButton.setContentAreaFilled(false);
        signinButton.setBorderPainted(false);
        signinButton.setFocusPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        logoPanel = new java.awt.Panel();
        logoLabel = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        signinLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JButton();
        showCheckBox = new javax.swing.JCheckBox();
        passLabel1 = new javax.swing.JLabel();
        newPasswordField1 = new javax.swing.JPasswordField();
        showCheckBox1 = new javax.swing.JCheckBox();
        haveLabel = new javax.swing.JLabel();
        signinButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempPanel.setBackground(new java.awt.Color(255, 255, 255));
        tempPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        tempPanel.setLayout(null);

        leftPanel.setBackground(new java.awt.Color(250, 239, 217));
        leftPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        leftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeLabel.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(80, 60, 40));
        welcomeLabel.setText("Welcome back");
        leftPanel.add(welcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        noteLabel.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        noteLabel.setForeground(new java.awt.Color(80, 60, 40));
        noteLabel.setText("<html><div style='text-align:center;'>We're happy to have you back.<br>Please sign in to explore the latest content.</div></html> ");
        leftPanel.add(noteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 330, 48));

        logoPanel.setBackground(new java.awt.Color(250, 239, 217));
        logoPanel.setLayout(null);

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/8.png"))); // NOI18N
        logoPanel.add(logoLabel);
        logoLabel.setBounds(0, 0, 400, 410);

        leftPanel.add(logoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        tempPanel.add(leftPanel);
        leftPanel.setBounds(0, 0, 400, 500);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setPreferredSize(new java.awt.Dimension(400, 500));

        signinLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signinLabel.setForeground(new java.awt.Color(80, 60, 40));
        signinLabel.setText("FORGOT PASSWORD");

        emailLabel.setBackground(new java.awt.Color(102, 102, 102));
        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailLabel.setText("Email");

        emailTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(102, 102, 102));
        emailTextField.setText("Enter email");
        emailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTextFieldFocusLost(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passLabel.setBackground(new java.awt.Color(102, 102, 102));
        passLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passLabel.setText("New password");

        newPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPasswordField.setText("Enter password");
        newPasswordField.setToolTipText("");
        newPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordFieldFocusLost(evt);
            }
        });
        newPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordFieldActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(40, 167, 69));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setFocusPainted(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        showCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showCheckBox.setText("Show password");
        showCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCheckBoxActionPerformed(evt);
            }
        });

        passLabel1.setBackground(new java.awt.Color(102, 102, 102));
        passLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        passLabel1.setText("Check new password");

        newPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newPasswordField1.setText("Enter password");
        newPasswordField1.setToolTipText("");
        newPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                newPasswordField1FocusLost(evt);
            }
        });
        newPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordField1ActionPerformed(evt);
            }
        });

        showCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        showCheckBox1.setText("Show password");
        showCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showCheckBox1ActionPerformed(evt);
            }
        });

        haveLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        haveLabel.setText("Don't forgot password?");

        signinButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        signinButton.setForeground(new java.awt.Color(0, 0, 255));
        signinButton.setText("Sign In");
        signinButton.setBorder(null);
        signinButton.setBorderPainted(false);
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showCheckBox1)
                            .addComponent(passLabel1)
                            .addComponent(newPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(signinLabel)
                            .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(showCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(passLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newPasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(saveButton)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(haveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signinButton)
                .addGap(98, 98, 98))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(signinLabel)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCheckBox)
                .addGap(18, 18, 18)
                .addComponent(passLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(haveLabel)
                    .addComponent(signinButton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tempPanel.add(rightPanel);
        rightPanel.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusGained
        // TODO add your handling code here:
        if (emailTextField.getText().equals("Enter email")) {
            emailTextField.setText("");
            emailTextField.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_emailTextFieldFocusGained

    private void emailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTextFieldFocusLost
        // TODO add your handling code here:
        if (emailTextField.getText().equals("")) {
            emailTextField.setText("Enter email");
            emailTextField.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_emailTextFieldFocusLost

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void newPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFieldFocusGained
        // TODO add your handling code here: PasswordField
        if (String.valueOf(newPasswordField.getPassword()).equals("Enter password")) {
            newPasswordField.setText("");
            newPasswordField.setForeground(new Color(102, 102, 102));
            newPasswordField.setEchoChar('●');
        }
    }//GEN-LAST:event_newPasswordFieldFocusGained

    private void newPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFieldFocusLost
        // TODO add your handling code here:
        if (newPasswordField.getPassword().length < 1) {
            newPasswordField.setEchoChar((char)0);
            newPasswordField.setText("Enter password");
            newPasswordField.setForeground(new Color(102, 102, 102));
        }
    }//GEN-LAST:event_newPasswordFieldFocusLost

    private void newPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String email = emailTextField.getText();
        String password = new String(newPasswordField.getPassword());
        String password1 = new String(newPasswordField1.getPassword());
        
        if (email.equals("Enter email") || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.equals("Enter password") || password.isEmpty() ||
            password1.equals("Enter password") || password1.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ mật khẩu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(password1)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void showCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCheckBoxActionPerformed
        // TODO add your handling code here:showCheckBox
        if(showCheckBox.isSelected()) {
            newPasswordField.setEchoChar((char)0);
        }
        else {
            newPasswordField.setEchoChar('●');
        }
    }//GEN-LAST:event_showCheckBoxActionPerformed

    private void newPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordField1FocusGained
        // TODO add your handling code here:
        if (String.valueOf(newPasswordField1.getPassword()).equals("Enter password")) {
            newPasswordField1.setText("");
            newPasswordField1.setForeground(new Color(102, 102, 102));
            newPasswordField1.setEchoChar('●');
        }
    }//GEN-LAST:event_newPasswordField1FocusGained

    private void newPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordField1FocusLost
        // TODO add your handling code here:
        if (newPasswordField1.getPassword().length < 1) {
            newPasswordField1.setEchoChar((char)0);
            newPasswordField1.setText("Enter password");
            newPasswordField1.setForeground(new Color(102, 102, 102));
        }
        
    }//GEN-LAST:event_newPasswordField1FocusLost

    private void newPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordField1ActionPerformed

    private void showCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(showCheckBox1.isSelected()) {
            newPasswordField1.setEchoChar((char)0);
        }
        else {
            newPasswordField1.setEchoChar('●');
        }
    }//GEN-LAST:event_showCheckBox1ActionPerformed

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        C_Signin SigninFrame = new C_Signin();
        SigninFrame.setVisible(true);
        SigninFrame.pack();
        SigninFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_signinButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(C_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(C_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(C_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(C_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new C_ForgotPassword().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel haveLabel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoLabel;
    private java.awt.Panel logoPanel;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField newPasswordField1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox showCheckBox;
    private javax.swing.JCheckBox showCheckBox1;
    private javax.swing.JButton signinButton;
    private javax.swing.JLabel signinLabel;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
