
package View;

import controller.DanhMucBean;
import controller.C_ChuyenManHinhController;
import java.util.ArrayList;
import java.util.List;
import model.TaiKhoan;
/**
 *
 * @author nttma
 */
public class C_Homepage extends javax.swing.JFrame {

    private TaiKhoan taiKhoan;
    
    private C_homePanel homeCustomPanel;
    private C_menuPanel menuCustomPanel;
    private C_historyPanel historyCustomPanel;
    private C_profilePanel profileCustomPanel;

    
    public C_Homepage(TaiKhoan tk) {
        this();
        this.taiKhoan = tk;
        
        homeCustomPanel.setTaiKhoan(taiKhoan);
        menuCustomPanel.setTaiKhoan(taiKhoan);
        historyCustomPanel.setTaiKhoan(taiKhoan);
        profileCustomPanel.setTaiKhoan(taiKhoan);
        
        System.out.println("Đăng nhập với tài khoản: " + tk.getEmail());
        
        C_ChuyenManHinhController controller = new C_ChuyenManHinhController(rightPanel);
        controller.setTaiKhoan(taiKhoan);

        controller.setView(homeCustomPanel, homeLabel);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("Home", homeCustomPanel, homeLabel));
        listItem.add(new DanhMucBean("Menu", menuCustomPanel, menuLabel));
        listItem.add(new DanhMucBean("Deal", discountPanel, discountLabel)); 
        listItem.add(new DanhMucBean("History", historyCustomPanel, historyLabel));
        listItem.add(new DanhMucBean("Profile", profileCustomPanel, profileLabel));
        
        controller.setEvent(listItem);
                
    }
    /**
     * Creates new form C_Homepage
     */
    public C_Homepage() {
        initComponents();
        
        homeCustomPanel = new C_homePanel();
        menuCustomPanel = new C_menuPanel() {};
        historyCustomPanel = new C_historyPanel();
        profileCustomPanel = new C_profilePanel();

        C_ChuyenManHinhController controller = new C_ChuyenManHinhController(rightPanel);
        controller.setView(homeCustomPanel, homeLabel);
        
        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("Home", homeCustomPanel, homeLabel));
        listItem.add(new DanhMucBean("Menu", menuCustomPanel, menuLabel));
        listItem.add(new DanhMucBean("Deal", discountPanel, discountLabel)); 
        listItem.add(new DanhMucBean("History", historyCustomPanel, historyLabel));
        listItem.add(new DanhMucBean("Profile", profileCustomPanel, profileLabel));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        discountPanel = new javax.swing.JPanel();
        discountLabel = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        historyLabel = new javax.swing.JLabel();
        profilePanel = new javax.swing.JPanel();
        profileLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tempPanel.setBackground(new java.awt.Color(255, 255, 255));
        tempPanel.setPreferredSize(new java.awt.Dimension(1100, 750));
        tempPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leftPanel.setBackground(new java.awt.Color(149, 114, 90));
        leftPanel.setPreferredSize(new java.awt.Dimension(100, 750));
        leftPanel.setLayout(null);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/logo100.png"))); // NOI18N
        leftPanel.add(logoLabel);
        logoLabel.setBounds(0, 0, 100, 100);

        homePanel.setBackground(new java.awt.Color(245, 245, 220));
        homePanel.setLayout(null);

        homeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/home30.png"))); // NOI18N
        homeLabel.setText("Home");
        homeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        homeLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        homePanel.add(homeLabel);
        homeLabel.setBounds(6, 6, 70, 70);

        leftPanel.add(homePanel);
        homePanel.setBounds(9, 112, 82, 82);

        menuPanel.setBackground(new java.awt.Color(245, 245, 220));
        menuPanel.setLayout(null);

        menuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/menu30.png"))); // NOI18N
        menuLabel.setText("Menu");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        menuLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menuPanel.add(menuLabel);
        menuLabel.setBounds(6, 6, 70, 70);

        leftPanel.add(menuPanel);
        menuPanel.setBounds(9, 206, 82, 82);

        discountPanel.setBackground(new java.awt.Color(245, 245, 220));
        discountPanel.setLayout(null);

        discountLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        discountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        discountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/discount30.png"))); // NOI18N
        discountLabel.setText("Deal");
        discountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        discountLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        discountLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        discountPanel.add(discountLabel);
        discountLabel.setBounds(6, 6, 70, 70);

        leftPanel.add(discountPanel);
        discountPanel.setBounds(9, 300, 82, 82);

        historyPanel.setBackground(new java.awt.Color(245, 245, 220));
        historyPanel.setLayout(null);

        historyLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        historyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/history30.png"))); // NOI18N
        historyLabel.setText("History");
        historyLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historyLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        historyLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        historyPanel.add(historyLabel);
        historyLabel.setBounds(6, 6, 70, 70);

        leftPanel.add(historyPanel);
        historyPanel.setBounds(9, 394, 82, 82);

        profilePanel.setBackground(new java.awt.Color(245, 245, 220));
        profilePanel.setLayout(null);

        profileLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        profileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/profile30.png"))); // NOI18N
        profileLabel.setText("Profile");
        profileLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profileLabel.setPreferredSize(new java.awt.Dimension(70, 70));
        profileLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        profilePanel.add(profileLabel);
        profileLabel.setBounds(6, 6, 70, 70);

        leftPanel.add(profilePanel);
        profilePanel.setBounds(9, 488, 82, 82);

        logoutButton.setBackground(new java.awt.Color(149, 114, 90));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(252, 252, 246));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/logout30.png"))); // NOI18N
        logoutButton.setText("Log out");
        logoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 252, 246)));
        logoutButton.setFocusPainted(false);
        logoutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        leftPanel.add(logoutButton);
        logoutButton.setBounds(9, 662, 82, 82);

        tempPanel.add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 750));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        tempPanel.add(rightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 1000, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        C_Signin SigninFrame = new C_Signin();
        SigninFrame.setVisible(true);
        SigninFrame.pack();
        SigninFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discountLabel;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JLabel historyLabel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel profileLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel tempPanel;
    // End of variables declaration//GEN-END:variables
}
