
package View;

import controller.HoaDonController;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CT_HoaDon;
import model.HoaDon;

/**
 *
 * @author nttma
 */
public class E_bill_update extends javax.swing.JFrame {

    private final HoaDon hoaDon;
    private final List<CT_HoaDon> chiTietList;
    private final E_billPanel hoaDonView;

    public E_bill_update(HoaDon hoaDon, List<CT_HoaDon> chiTietList, E_billPanel hoaDonView) {
        initComponents();
        
        this.hoaDon = hoaDon;
        this.chiTietList = chiTietList;
        this.hoaDonView = hoaDonView;
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            String maMon = (String) jTable1.getValueAt(selectedRow, 1);
            double donGia = (double) jTable1.getValueAt(selectedRow, 2);
            int soLuong = (int) jTable1.getValueAt(selectedRow, 3);
            double thanhTien = (double) jTable1.getValueAt(selectedRow, 4);

            item_idTextField.setText(maMon);
            priceTextField.setText(String.valueOf(donGia));
            quantityTextField.setText(String.valueOf(soLuong));
            amountTextField.setText(String.valueOf(thanhTien));
            
        }
    });

        loadDataToForm();
    }
    
    private void loadDataToForm() {
        idTextField.setText(hoaDon.getMaHD());
        idTextField.setEditable(false);

        createdDateChooser.setDate(hoaDon.getNgayLap());
        empTextField.setText(hoaDon.getMaNV());
        ctTextField.setText(hoaDon.getMaKH());
        dis_idTextField.setText(hoaDon.getMaKM());
        disTextField.setText(String.valueOf(hoaDon.getTienGiamGia()));
        subTextField.setText(String.valueOf(hoaDon.getTongTienTruoc()));
        totalTextField.setText(String.valueOf(hoaDon.getTongTienSau()));
        paymentTextField.setText(hoaDon.getHinhThucTT());
        noteTextField.setText(hoaDon.getGhiChu());

        loadChiTietTable(chiTietList);
    }
    
    private void loadChiTietTable(List<CT_HoaDon> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (CT_HoaDon ct : list) {
            Object[] row = new Object[]{
                ct.getMaHD(),
                ct.getMaMon(),
                ct.getDonGia(),
                ct.getSoLuong(),
                ct.getSoLuong() * ct.getDonGia()
            };
            model.addRow(row);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        createdLabel = new javax.swing.JLabel();
        empLabel = new javax.swing.JLabel();
        empTextField = new javax.swing.JTextField();
        ctLabel = new javax.swing.JLabel();
        ctTextField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        totalTextField = new javax.swing.JTextField();
        createdDateChooser = new com.toedter.calendar.JDateChooser();
        temp1Panel = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        subLabel = new javax.swing.JLabel();
        subTextField = new javax.swing.JTextField();
        disLabel = new javax.swing.JLabel();
        disTextField = new javax.swing.JTextField();
        paymentLabel = new javax.swing.JLabel();
        paymentTextField = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        noteTextField = new javax.swing.JTextField();
        dis_idLabel = new javax.swing.JLabel();
        dis_idTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        item_idLabel = new javax.swing.JLabel();
        item_idTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        amoutLabel = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(1100, 750));

        addLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        addLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addLabel.setText("update BILL");

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        idLabel.setText("ID:");

        idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(102, 102, 102));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        createdLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        createdLabel.setText("Created date:");

        empLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        empLabel.setText("Employee ID:");

        empTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        empTextField.setForeground(new java.awt.Color(102, 102, 102));
        empTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTextFieldActionPerformed(evt);
            }
        });

        ctLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ctLabel.setText("Customer ID:");

        ctTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ctTextField.setForeground(new java.awt.Color(102, 102, 102));
        ctTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctTextFieldActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalLabel.setText("Total:");

        totalTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalTextField.setForeground(new java.awt.Color(102, 102, 102));
        totalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextFieldActionPerformed(evt);
            }
        });

        createdDateChooser.setForeground(new java.awt.Color(102, 102, 102));

        temp1Panel.setBackground(new java.awt.Color(252, 252, 246));

        insertButton.setBackground(new java.awt.Color(250, 239, 217));
        insertButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        insertButton.setForeground(new java.awt.Color(80, 60, 40));
        insertButton.setText("Save");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(250, 239, 217));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(80, 60, 40));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temp1PanelLayout = new javax.swing.GroupLayout(temp1Panel);
        temp1Panel.setLayout(temp1PanelLayout);
        temp1PanelLayout.setHorizontalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temp1PanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        temp1PanelLayout.setVerticalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        subLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        subLabel.setText("Subtotal:");

        subTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subTextField.setForeground(new java.awt.Color(102, 102, 102));
        subTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTextFieldActionPerformed(evt);
            }
        });

        disLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        disLabel.setText("Discount:");

        disTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disTextField.setForeground(new java.awt.Color(102, 102, 102));
        disTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disTextFieldActionPerformed(evt);
            }
        });

        paymentLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        paymentLabel.setText("Payment:");

        paymentTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentTextField.setForeground(new java.awt.Color(102, 102, 102));
        paymentTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentTextFieldActionPerformed(evt);
            }
        });

        noteLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        noteLabel.setText("Note:");

        noteTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteTextField.setForeground(new java.awt.Color(102, 102, 102));
        noteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTextFieldActionPerformed(evt);
            }
        });

        dis_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dis_idLabel.setText("Discount ID:");

        dis_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dis_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        dis_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dis_idTextFieldActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        item_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        item_idLabel.setText("Item ID:");

        item_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        item_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        item_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_idTextFieldActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quantityLabel.setText("Quantity:");

        quantityTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityTextField.setForeground(new java.awt.Color(102, 102, 102));
        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        priceLabel.setText("Price:");

        priceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceTextField.setForeground(new java.awt.Color(102, 102, 102));
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        amoutLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        amoutLabel.setText("Amount:");

        amountTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amountTextField.setForeground(new java.awt.Color(102, 102, 102));
        amountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextFieldActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Item ID", "Price", "Quantity", "Amount"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        updateButton.setBackground(new java.awt.Color(250, 239, 217));
        updateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        updateButton.setForeground(new java.awt.Color(80, 60, 40));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tempPanelLayout = new javax.swing.GroupLayout(tempPanel);
        tempPanel.setLayout(tempPanelLayout);
        tempPanelLayout.setHorizontalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createdLabel)
                            .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(tempPanelLayout.createSequentialGroup()
                                    .addComponent(dis_idLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dis_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(tempPanelLayout.createSequentialGroup()
                                    .addComponent(ctLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ctTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(paymentLabel)
                            .addComponent(totalLabel)
                            .addComponent(disLabel)
                            .addComponent(subLabel)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(createdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tempPanelLayout.createSequentialGroup()
                                    .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tempPanelLayout.createSequentialGroup()
                                            .addComponent(empLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempPanelLayout.createSequentialGroup()
                                            .addComponent(noteLabel)
                                            .addGap(63, 63, 63)))
                                    .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(empTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(noteTextField)))
                                .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(disTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(temp1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tempPanelLayout.createSequentialGroup()
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityLabel)
                                    .addComponent(item_idLabel)
                                    .addComponent(priceLabel)
                                    .addComponent(amoutLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(item_idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(quantityTextField)
                                    .addComponent(priceTextField)
                                    .addComponent(amountTextField)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(addLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tempPanelLayout.setVerticalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(addLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(item_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(item_idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amoutLabel))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paymentLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tempPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(createdLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noteLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dis_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dis_idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(temp1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void empTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTextFieldActionPerformed

    private void ctTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctTextFieldActionPerformed

    private void totalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTextFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        String maHD = idTextField.getText();
        Date ngayLap = createdDateChooser.getDate();
        String maNV = empTextField.getText();
        String maKH = ctTextField.getText();
        String maKM = dis_idTextField.getText();
        double tienGiamGia = Double.parseDouble(disTextField.getText());
        double tongTruoc = Double.parseDouble(subTextField.getText());
        double tongSau = Double.parseDouble(totalTextField.getText());
        String hinhThucTT = paymentTextField.getText();
        String ghiChu = noteTextField.getText();

        HoaDon hd = new HoaDon(maHD, tongTruoc, tienGiamGia, tongSau, hinhThucTT, ngayLap, ghiChu, maKH, maNV, maKM);

        List<CT_HoaDon> updatedChiTietList = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            String maMon = model.getValueAt(i, 1).toString();
            double donGia = Double.parseDouble(model.getValueAt(i, 2).toString());
            int soLuong = Integer.parseInt(model.getValueAt(i, 3).toString());

            updatedChiTietList.add(new CT_HoaDon(maHD, maMon, donGia, soLuong));
        }

        HoaDonController controller = new HoaDonController(this, hoaDonView);
        controller.updateHoaDon(hd, updatedChiTietList);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        E_billPanel ordersPanel = new E_billPanel();
        ordersPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void subTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTextFieldActionPerformed

    private void disTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disTextFieldActionPerformed

    private void paymentTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentTextFieldActionPerformed

    private void noteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTextFieldActionPerformed

    private void dis_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dis_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dis_idTextFieldActionPerformed

    private void item_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_idTextFieldActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void amountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String maMon = item_idTextField.getText().trim();
        String soLuongStr = quantityTextField.getText().trim();
        String donGiaStr = priceTextField.getText().trim();
        String maHD = idTextField.getText().trim();

        if (maMon.isEmpty() || soLuongStr.isEmpty() || donGiaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin chi tiết.");
            return;
        }

        try {
            int soLuong = Integer.parseInt(soLuongStr);
            double donGia = Double.parseDouble(donGiaStr);
            double thanhTien = soLuong * donGia;

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int selectedRow = jTable1.getSelectedRow();

            if (selectedRow != -1) {
                model.setValueAt(maHD, selectedRow, 0);
                model.setValueAt(maMon, selectedRow, 1);
                model.setValueAt(donGia, selectedRow, 2);
                model.setValueAt(soLuong, selectedRow, 3);
                model.setValueAt(thanhTien, selectedRow, 4);
            } else {
                Object[] row = {maHD, maMon, donGia, soLuong, thanhTien};
                model.addRow(row);
            }

            jTable1.clearSelection();
            item_idTextField.setText("");
            priceTextField.setText("");
            quantityTextField.setText("");
            amountTextField.setText("");
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng hoặc đơn giá không hợp lệ.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(E_bill_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(E_bill_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(E_bill_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(E_bill_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new E_bill_update().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JLabel amoutLabel;
    private javax.swing.JButton cancelButton;
    private com.toedter.calendar.JDateChooser createdDateChooser;
    private javax.swing.JLabel createdLabel;
    private javax.swing.JLabel ctLabel;
    private javax.swing.JTextField ctTextField;
    private javax.swing.JLabel disLabel;
    private javax.swing.JTextField disTextField;
    private javax.swing.JLabel dis_idLabel;
    private javax.swing.JTextField dis_idTextField;
    private javax.swing.JLabel empLabel;
    private javax.swing.JTextField empTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton insertButton;
    private javax.swing.JLabel item_idLabel;
    private javax.swing.JTextField item_idTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JLabel subLabel;
    private javax.swing.JTextField subTextField;
    private javax.swing.JPanel temp1Panel;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
