
package View;

import controller.TaiKhoanController;
import dao.TaiKhoanDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TaiKhoan;

/**
 *
 * @author nttma
 */
public class E_home_U extends javax.swing.JFrame {
    
    private final TaiKhoanDAO taiKhoanDAO = new TaiKhoanDAO();

    public void loadAll() {
        List<TaiKhoan> list = taiKhoanDAO.findAll();

        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.setRowCount(0);

        for (TaiKhoan tk : list) {
            Object[] row = new Object[]{
                tk.getMaTK(),    
                tk.getEmail(),     
                tk.getMatKhau(),  
                tk.getLoaiTK(),  
                tk.getTrangThai()  
            };
            model.addRow(row);
        }
    }

    public TaiKhoan getSelectedTaiKhoan() {
        int selectedRow = userTable.getSelectedRow();
        if (selectedRow == -1) return null;

        DefaultTableModel model = (DefaultTableModel) userTable.getModel();

        String matk = (String) model.getValueAt(selectedRow, 0);
        String email = (String) model.getValueAt(selectedRow, 1);
        String matkhau = (String) model.getValueAt(selectedRow, 2);
        String loaitk = (String) model.getValueAt(selectedRow, 3);
        String trangthai = (String) model.getValueAt(selectedRow, 4);

        return new TaiKhoan(matk, email, matkhau, loaitk, trangthai);
    }

    /**
     * Creates new form E_home_U
     */
    public E_home_U() {
        initComponents();
        
        loadAll();
        
        insertButton.setContentAreaFilled(false);
        insertButton.setBorderPainted(false);
        insertButton.setFocusPainted(false);
        
        updateButton.setContentAreaFilled(false);
        updateButton.setBorderPainted(false);
        updateButton.setFocusPainted(false);
        
        deleteButton.setContentAreaFilled(false);
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        
        detailButton.setContentAreaFilled(false);
        detailButton.setBorderPainted(false);
        detailButton.setFocusPainted(false);
        
        returnButton.setContentAreaFilled(false);
        returnButton.setBorderPainted(false);
        returnButton.setFocusPainted(false);
        
        TableSearchUtil.enableSearch(userTable, searchTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        userScrollPane = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        search1Panel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        search2Panel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        allTextField = new javax.swing.JTextField();
        userLabel = new javax.swing.JLabel();
        action1Panel = new javax.swing.JPanel();
        actionLabel1 = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(800, 750));
        tempPanel.setLayout(null);

        userTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Email", "Password", "Type", "Status"
            }
        ));
        userTable.setRowHeight(30);
        userScrollPane.setViewportView(userTable);

        tempPanel.add(userScrollPane);
        userScrollPane.setBounds(10, 212, 780, 530);

        search1Panel.setBackground(new java.awt.Color(252, 252, 246));

        searchLabel.setBackground(new java.awt.Color(252, 252, 246));
        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        javax.swing.GroupLayout search1PanelLayout = new javax.swing.GroupLayout(search1Panel);
        search1Panel.setLayout(search1PanelLayout);
        search1PanelLayout.setHorizontalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        search1PanelLayout.setVerticalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search1PanelLayout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(search1Panel);
        search1Panel.setBounds(40, 110, 60, 20);

        search2Panel.setBackground(new java.awt.Color(252, 252, 246));
        search2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        allTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        allTextField.setForeground(new java.awt.Color(102, 102, 102));
        allTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search2PanelLayout = new javax.swing.GroupLayout(search2Panel);
        search2Panel.setLayout(search2PanelLayout);
        search2PanelLayout.setHorizontalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(allTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        search2PanelLayout.setVerticalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tempPanel.add(search2Panel);
        search2Panel.setBounds(20, 120, 520, 60);

        userLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setText("User Account Management");
        tempPanel.add(userLabel);
        userLabel.setBounds(0, 70, 800, 33);

        action1Panel.setBackground(new java.awt.Color(252, 252, 246));

        actionLabel1.setBackground(new java.awt.Color(252, 252, 246));
        actionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actionLabel1.setText("Action");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action1PanelLayout.createSequentialGroup()
                .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(action1Panel);
        action1Panel.setBounds(590, 110, 60, 20);

        action2Panel.setBackground(new java.awt.Color(252, 252, 246));
        action2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add_30.png"))); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/update30.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/delete30.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        detailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/detail30.png"))); // NOI18N
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        tempPanel.add(action2Panel);
        action2Panel.setBounds(570, 120, 210, 60);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/return20.png"))); // NOI18N
        returnButton.setFocusPainted(false);
        returnButton.setPreferredSize(new java.awt.Dimension(30, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        jPanel2.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tempPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void allTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allTextFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        E_home_U_insert insertFrame = new E_home_U_insert(this);
        insertFrame.setVisible(true);
        insertFrame.pack();
        insertFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        TaiKhoan selected = getSelectedTaiKhoan();
        if (selected != null) {
            E_home_U_update updateFrame = new E_home_U_update(selected, this);
            updateFrame.setVisible(true);
            updateFrame.pack();
            updateFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một tài khoản để cập nhật.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        TaiKhoan selected = getSelectedTaiKhoan();
        if (selected == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

        TaiKhoanController controller = new TaiKhoanController(this, this);
        controller.deleteTaiKhoan(selected.getMaTK(), this::loadAll);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        TaiKhoan selected = getSelectedTaiKhoan();
        if (selected != null) {
            E_home_U_detail detailFrame = new E_home_U_detail(selected);
            detailFrame.setVisible(true);
            detailFrame.pack();
            detailFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một tài khoản để xem chi tiết.");
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        E_homePanel homePanel = new E_homePanel();
        homePanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JLabel actionLabel1;
    private javax.swing.JTextField allTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel search1Panel;
    private javax.swing.JPanel search2Panel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JScrollPane userScrollPane;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
