
package View;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.CT_PhieuKho;
import model.PhieuKho;

/**
 *
 * @author nttma
 */
public class E_home_IE_detail extends javax.swing.JFrame {

    private E_home_IE parent;
    
    public E_home_IE_detail(E_home_IE parent) {
        initComponents();
        this.parent = parent;
    }
    
    public E_home_IE_detail(PhieuKho pk, List<CT_PhieuKho> chiTietList) {
        initComponents();
        
        ie_idTextField.setText(pk.getMaPhieu());
        transactionDateChooser.setDate(pk.getNgayGiaoDich());
        typeComboBox.setSelectedItem(pk.getLoaiPhieu());
        e_idTextField.setText(pk.getMaNV());
        e_idTextField1.setText(String.valueOf(pk.getTongTien()));
        noteTextField.setText(pk.getGhiChu());

        // Khóa chỉnh sửa
        ie_idTextField.setEditable(false);
        transactionDateChooser.setEnabled(false);
        typeComboBox.setEnabled(false);
        e_idTextField.setEditable(false);
        e_idTextField1.setEditable(false);
        noteTextField.setEditable(false);

        loadChiTietTable(chiTietList);
    }
    
    private void loadChiTietTable(List<CT_PhieuKho> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (CT_PhieuKho ct : list) {
            double thanhTien = ct.getSoLuong() * ct.getDonGia();
            Object[] row = new Object[] {
                ct.getMaPhieu(),
                ct.getMaSP(),
                ct.getSoLuong(),
                ct.getDonGia(),
                thanhTien
            };
            model.addRow(row);
        }

        jTable1.setEnabled(true);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int selectedRow = jTable1.getSelectedRow();
                DefaultTableModel selectedModel = (DefaultTableModel) jTable1.getModel();

                String maSP = selectedModel.getValueAt(selectedRow, 1).toString();
                String soLuong = selectedModel.getValueAt(selectedRow, 2).toString();
                String donGia = selectedModel.getValueAt(selectedRow, 3).toString();

                ie_item_idTextField.setText(maSP);
                quantityTextField.setText(soLuong);
                priceTextField.setText(donGia);
                
                ie_item_idTextField.setEditable(false);
                quantityTextField.setEditable(false);
                priceTextField.setEditable(false);
            }
        });
    }
    
    public E_home_IE_detail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        detailLabel = new javax.swing.JLabel();
        ie_idLabel = new javax.swing.JLabel();
        ie_idTextField = new javax.swing.JTextField();
        transactionLabel = new javax.swing.JLabel();
        e_idLabel = new javax.swing.JLabel();
        e_idTextField = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        noteTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        transactionDateChooser = new com.toedter.calendar.JDateChooser();
        temp1Panel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        ie_item_idLabel = new javax.swing.JLabel();
        ie_item_idTextField = new javax.swing.JTextField();
        quantityLabel = new javax.swing.JLabel();
        quantityTextField = new javax.swing.JTextField();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        e_idLabel1 = new javax.swing.JLabel();
        e_idTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(538, 471));

        detailLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        detailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailLabel.setText("detail");

        ie_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ie_idLabel.setText("ID:");

        ie_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ie_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        ie_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ie_idTextFieldActionPerformed(evt);
            }
        });

        transactionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        transactionLabel.setText("Transaction date:");

        e_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        e_idLabel.setText("Employee ID:");

        e_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        e_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        e_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_idTextFieldActionPerformed(evt);
            }
        });

        noteLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        noteLabel.setText("Note:");

        noteTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        noteTextField.setForeground(new java.awt.Color(102, 102, 102));
        noteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteTextFieldActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        typeLabel.setText("Type:");

        transactionDateChooser.setForeground(new java.awt.Color(102, 102, 102));

        temp1Panel.setBackground(new java.awt.Color(252, 252, 246));

        cancelButton.setBackground(new java.awt.Color(173, 181, 189));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(33, 37, 41));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temp1PanelLayout = new javax.swing.GroupLayout(temp1Panel);
        temp1Panel.setLayout(temp1PanelLayout);
        temp1PanelLayout.setHorizontalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323))
        );
        temp1PanelLayout.setVerticalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        typeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NHAP", "XUAT" }));
        typeComboBox.setOpaque(true);
        typeComboBox.setPreferredSize(new java.awt.Dimension(76, 40));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Item ID", "Quantity", "Price"
            }
        ));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ie_item_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ie_item_idLabel.setText("Item ID:");

        ie_item_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ie_item_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        ie_item_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ie_item_idTextFieldActionPerformed(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        quantityLabel.setText("Quantity:");

        quantityTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityTextField.setForeground(new java.awt.Color(102, 102, 102));
        quantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextFieldActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        priceLabel.setText("Price:");

        priceTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceTextField.setForeground(new java.awt.Color(102, 102, 102));
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        e_idLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        e_idLabel1.setText("Total:");

        e_idTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        e_idTextField1.setForeground(new java.awt.Color(102, 102, 102));
        e_idTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_idTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tempPanelLayout = new javax.swing.GroupLayout(tempPanel);
        tempPanel.setLayout(tempPanelLayout);
        tempPanelLayout.setHorizontalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addComponent(transactionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addComponent(ie_idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(ie_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeLabel)
                            .addComponent(e_idLabel)
                            .addComponent(e_idLabel1)
                            .addComponent(noteLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(e_idTextField1)
                            .addComponent(e_idTextField)
                            .addComponent(typeComboBox, 0, 250, Short.MAX_VALUE)
                            .addComponent(noteTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(19, 19, 19)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tempPanelLayout.createSequentialGroup()
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ie_item_idLabel)
                                    .addComponent(quantityLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(quantityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(ie_item_idTextField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(detailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(temp1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        tempPanelLayout.setVerticalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(detailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ie_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ie_idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(transactionDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tempPanelLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(transactionLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(typeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(e_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_idLabel))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(e_idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e_idLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noteLabel))
                        .addGap(30, 30, 30))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tempPanelLayout.createSequentialGroup()
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ie_item_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ie_item_idLabel))
                                .addGap(18, 18, 18)
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantityLabel))
                                .addGap(18, 18, 18)
                                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceLabel))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(temp1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ie_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ie_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ie_idTextFieldActionPerformed

    private void e_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_idTextFieldActionPerformed

    private void noteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (parent != null) {
            parent.setVisible(true); 
        }
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void ie_item_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ie_item_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ie_item_idTextFieldActionPerformed

    private void quantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void e_idTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_idTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_idTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel detailLabel;
    private javax.swing.JLabel e_idLabel;
    private javax.swing.JLabel e_idLabel1;
    private javax.swing.JTextField e_idTextField;
    private javax.swing.JTextField e_idTextField1;
    private javax.swing.JLabel ie_idLabel;
    private javax.swing.JTextField ie_idTextField;
    private javax.swing.JLabel ie_item_idLabel;
    private javax.swing.JTextField ie_item_idTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextField noteTextField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JPanel temp1Panel;
    private javax.swing.JPanel tempPanel;
    private com.toedter.calendar.JDateChooser transactionDateChooser;
    private javax.swing.JLabel transactionLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
