
package View;

//import View.TableButton.ButtonEditor;
//import View.TableButton.ButtonRenderer;
//import javax.swing.JCheckBox;
import controller.SanPhamController;
import dao.SanPhamDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SanPham;

/**
 *
 * @author nttma
 */
public class E_inventoryPanel extends javax.swing.JPanel {

    public void loadAll() {
        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();
        model.setRowCount(0);

        List<SanPham> list = new SanPhamDAO().findAll();
        for (SanPham sp : list) {
            model.addRow(new Object[] {
                sp.getMaSP(),
                sp.getTenSP(),
                sp.getLoaiSP(),
                sp.getTongSL(),
                sp.getDonViTinh(),
                String.format("%,.0f", sp.getGiaNhap()),
                sp.getNgaySX(),
                sp.getHanSD(),
                sp.getTrangThai()
            });
        }
    }
    
    
    public SanPham getSelectedSanPham() {
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow == -1) return null;

        DefaultTableModel model = (DefaultTableModel) inventoryTable.getModel();

        String maSP = (String) model.getValueAt(selectedRow, 0);
        String tenSP = (String) model.getValueAt(selectedRow, 1);
        String loaiSP = (String) model.getValueAt(selectedRow, 2);

        int tongSL = 0;
        Object tongSLObj = model.getValueAt(selectedRow, 3);
        switch (tongSLObj) {
            case Integer integer -> tongSL = integer;
            case Number number -> tongSL = number.intValue();
            case String string -> {
                try {
                    tongSL = Integer.parseInt(string);
                } catch (NumberFormatException e) {
                    tongSL = 0;
                }
            }
            default -> {
            }
        }

        String donViTinh = (String) model.getValueAt(selectedRow, 4);

        String giaNhapStr = model.getValueAt(selectedRow, 5).toString().trim();
        giaNhapStr = giaNhapStr.replace("đ", "").replace(",", "").replace(".", "").trim();
        double giaNhap = 0;
        try {
            giaNhap = Double.parseDouble(giaNhapStr);
        } catch (NumberFormatException e) {
            giaNhap = 0;
        }

        java.util.Date ngaySX = (java.util.Date) model.getValueAt(selectedRow, 6);
        java.util.Date hanSD = (java.util.Date) model.getValueAt(selectedRow, 7);
        String trangThai = (String) model.getValueAt(selectedRow, 8);

        return new SanPham(maSP, tenSP, loaiSP, tongSL, donViTinh, giaNhap, ngaySX, hanSD, trangThai);
    }
    
    public E_inventoryPanel() {
        initComponents();

        loadAll();
        
        insertButton.setContentAreaFilled(false);
        insertButton.setBorderPainted(false);
        insertButton.setFocusPainted(false);
        
        updateButton.setContentAreaFilled(false);
        updateButton.setBorderPainted(false);
        updateButton.setFocusPainted(false);
        
        deleteButton.setContentAreaFilled(false);
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        
        detailButton.setContentAreaFilled(false);
        detailButton.setBorderPainted(false);
        detailButton.setFocusPainted(false);
        
        TableSearchUtil.enableSearch(inventoryTable, searchTextField);
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        inventoryScrollPane = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        search1Panel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        search2Panel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        allTextField = new javax.swing.JTextField();
        imLabel = new javax.swing.JLabel();
        date1Panel = new javax.swing.JPanel();
        date2Label = new javax.swing.JLabel();
        date2Panel = new javax.swing.JPanel();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        action1Panel = new javax.swing.JPanel();
        actionLabel1 = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(800, 750));
        tempPanel.setLayout(null);

        inventoryTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inventoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Quantity", "Unit", "Import Price", "MFD", "EXP", "Status"
            }
        ));
        inventoryTable.setRowHeight(30);
        inventoryScrollPane.setViewportView(inventoryTable);

        tempPanel.add(inventoryScrollPane);
        inventoryScrollPane.setBounds(10, 222, 780, 520);

        search1Panel.setBackground(new java.awt.Color(252, 252, 246));

        searchLabel.setBackground(new java.awt.Color(252, 252, 246));
        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        javax.swing.GroupLayout search1PanelLayout = new javax.swing.GroupLayout(search1Panel);
        search1Panel.setLayout(search1PanelLayout);
        search1PanelLayout.setHorizontalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        search1PanelLayout.setVerticalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search1PanelLayout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(search1Panel);
        search1Panel.setBounds(40, 50, 60, 20);

        search2Panel.setBackground(new java.awt.Color(252, 252, 246));
        search2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        allTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        allTextField.setForeground(new java.awt.Color(102, 102, 102));
        allTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search2PanelLayout = new javax.swing.GroupLayout(search2Panel);
        search2Panel.setLayout(search2PanelLayout);
        search2PanelLayout.setHorizontalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(allTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        search2PanelLayout.setVerticalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tempPanel.add(search2Panel);
        search2Panel.setBounds(20, 60, 760, 60);

        imLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        imLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imLabel.setText("Inventory Management");
        tempPanel.add(imLabel);
        imLabel.setBounds(0, 10, 800, 33);

        date1Panel.setBackground(new java.awt.Color(252, 252, 246));

        date2Label.setBackground(new java.awt.Color(252, 252, 246));
        date2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        date2Label.setText("Date");

        javax.swing.GroupLayout date1PanelLayout = new javax.swing.GroupLayout(date1Panel);
        date1Panel.setLayout(date1PanelLayout);
        date1PanelLayout.setHorizontalGroup(
            date1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(date1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(date2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        date1PanelLayout.setVerticalGroup(
            date1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, date1PanelLayout.createSequentialGroup()
                .addComponent(date2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(date1Panel);
        date1Panel.setBounds(40, 130, 50, 20);

        date2Panel.setBackground(new java.awt.Color(252, 252, 246));
        date2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        fromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromLabel.setText("From");

        toLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toLabel.setText("To");

        fromDateChooser.setPreferredSize(new java.awt.Dimension(64, 26));

        toDateChooser.setPreferredSize(new java.awt.Dimension(64, 26));

        javax.swing.GroupLayout date2PanelLayout = new javax.swing.GroupLayout(date2Panel);
        date2Panel.setLayout(date2PanelLayout);
        date2PanelLayout.setHorizontalGroup(
            date2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, date2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fromLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        date2PanelLayout.setVerticalGroup(
            date2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, date2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(date2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tempPanel.add(date2Panel);
        date2Panel.setBounds(20, 140, 390, 60);

        action1Panel.setBackground(new java.awt.Color(252, 252, 246));

        actionLabel1.setBackground(new java.awt.Color(252, 252, 246));
        actionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actionLabel1.setText("Action");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action1PanelLayout.createSequentialGroup()
                .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(action1Panel);
        action1Panel.setBounds(590, 130, 60, 20);

        action2Panel.setBackground(new java.awt.Color(252, 252, 246));
        action2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add_30.png"))); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/update30.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/delete30.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        detailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/detail30.png"))); // NOI18N
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        tempPanel.add(action2Panel);
        action2Panel.setBounds(570, 140, 210, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allTextFieldActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        E_inventory_insert inventoryFrame = new E_inventory_insert(this);
        inventoryFrame.setVisible(true);
        inventoryFrame.pack();
        inventoryFrame.setLocationRelativeTo(null);
//        this.dispose();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        SanPham selected = getSelectedSanPham(); // hàm bạn đã có tương tự getSelectedKhuyenMai
        if (selected != null) {
            // Mở form cập nhật sản phẩm, truyền sản phẩm và panel hiện tại để gọi lại loadAll() sau khi cập nhật
            E_inventory_update updateFrame = new E_inventory_update(selected, this);
            updateFrame.setVisible(true);
            updateFrame.pack();
            updateFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để cập nhật.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        int row = inventoryTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để xem chi tiết.");
            return;
        }

        String maSP = inventoryTable.getValueAt(row, 0).toString();
        SanPham sp = new SanPhamDAO().findById(maSP);

        if (sp != null) {
            E_inventory_detail detailFrame = new E_inventory_detail(sp);
            detailFrame.setVisible(true);
            detailFrame.pack();
            detailFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm.");
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = inventoryTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String maSP = inventoryTable.getValueAt(selectedRow, 0).toString();

        SanPhamController controller = new SanPhamController(this, this);
        controller.handleDelete(maSP, this::loadAll);
    }//GEN-LAST:event_deleteButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JLabel actionLabel1;
    private javax.swing.JTextField allTextField;
    private javax.swing.JPanel date1Panel;
    private javax.swing.JLabel date2Label;
    private javax.swing.JPanel date2Panel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailButton;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JLabel imLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JScrollPane inventoryScrollPane;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel search1Panel;
    private javax.swing.JPanel search2Panel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel tempPanel;
    private com.toedter.calendar.JDateChooser toDateChooser;
    private javax.swing.JLabel toLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
