
package View;

import model.KhuyenMai;

/**
 *
 * @author nttma
 */
public class E_voucher_detail extends javax.swing.JFrame {

    /**
     * Creates new form E_voucher_detail
     */
    public E_voucher_detail(KhuyenMai khuyenMai) {
        initComponents();
        
        setLocationRelativeTo(null);

        idTextField.setText(khuyenMai.getMaKM());
        nameTextField.setText(khuyenMai.getTenKM());
        typeTextField.setText(khuyenMai.getLoaiKM());

        if ("Giảm theo %".equals(khuyenMai.getLoaiKM())) {
            disTextField.setText(String.valueOf(khuyenMai.getGiaTriGiam()) + "%");
        } else {
            disTextField.setText(String.valueOf(khuyenMai.getGiaTriGiam()));
        }
        
        conditionTextField.setText(khuyenMai.getDieuKien());
        startDateChooser.setDate(khuyenMai.getNgayBD());
        endDateChooser.setDate(khuyenMai.getNgayKT());
        statusTextField.setText(khuyenMai.getTrangThai());

        // Không cho sửa
        idTextField.setEditable(false);
        nameTextField.setEditable(false);
        typeTextField.setEditable(false);
        disTextField.setEditable(false);
        conditionTextField.setEditable(false);
        startDateChooser.setEnabled(false);
        endDateChooser.setEnabled(false);
        statusTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        typeLabel = new javax.swing.JLabel();
        typeTextField = new javax.swing.JTextField();
        disLabel = new javax.swing.JLabel();
        disTextField = new javax.swing.JTextField();
        conditionLabel = new javax.swing.JLabel();
        conditionTextField = new javax.swing.JTextField();
        startLabel = new javax.swing.JLabel();
        startDateChooser = new com.toedter.calendar.JDateChooser();
        endLabel = new javax.swing.JLabel();
        endDateChooser = new com.toedter.calendar.JDateChooser();
        statusTextField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        temp1Panel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(1100, 750));

        infoLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("voucher information");

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        idLabel.setText("ID:");

        idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(102, 102, 102));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLabel.setText("Name:");

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(102, 102, 102));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        typeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        typeLabel.setText("Type:");

        typeTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        typeTextField.setForeground(new java.awt.Color(102, 102, 102));
        typeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeTextFieldActionPerformed(evt);
            }
        });

        disLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        disLabel.setText("Discount value:");

        disTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        disTextField.setForeground(new java.awt.Color(102, 102, 102));
        disTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disTextFieldActionPerformed(evt);
            }
        });

        conditionLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        conditionLabel.setText("Condition:");

        conditionTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        conditionTextField.setForeground(new java.awt.Color(102, 102, 102));
        conditionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conditionTextFieldActionPerformed(evt);
            }
        });

        startLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        startLabel.setText("Start date:");

        startDateChooser.setForeground(new java.awt.Color(102, 102, 102));

        endLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        endLabel.setText("End date:");

        endDateChooser.setForeground(new java.awt.Color(102, 102, 102));

        statusTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusTextField.setForeground(new java.awt.Color(102, 102, 102));
        statusTextField.setPreferredSize(new java.awt.Dimension(64, 40));

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        statusLabel.setText("Status:");

        temp1Panel.setBackground(new java.awt.Color(252, 252, 246));

        cancelButton.setBackground(new java.awt.Color(173, 181, 189));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(33, 37, 41));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temp1PanelLayout = new javax.swing.GroupLayout(temp1Panel);
        temp1Panel.setLayout(temp1PanelLayout);
        temp1PanelLayout.setHorizontalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        temp1PanelLayout.setVerticalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout tempPanelLayout = new javax.swing.GroupLayout(tempPanel);
        tempPanel.setLayout(tempPanelLayout);
        tempPanelLayout.setHorizontalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addComponent(temp1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLabel)
                            .addComponent(typeLabel)
                            .addComponent(conditionLabel)
                            .addComponent(startLabel)
                            .addComponent(endLabel)
                            .addComponent(statusLabel))
                        .addGap(44, 44, 44))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addComponent(disLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(disTextField)
                    .addComponent(conditionTextField)
                    .addComponent(nameTextField)
                    .addComponent(idTextField)
                    .addComponent(typeTextField)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(statusTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tempPanelLayout.setVerticalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conditionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempPanelLayout.createSequentialGroup()
                        .addComponent(startLabel)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tempPanelLayout.createSequentialGroup()
                        .addComponent(endLabel)
                        .addGap(10, 10, 10)))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addGap(36, 36, 36)
                .addComponent(temp1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void typeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeTextFieldActionPerformed

    private void disTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disTextFieldActionPerformed

    private void conditionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conditionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conditionTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        E_voucherPanel voucherPanel = new E_voucherPanel();
        voucherPanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel conditionLabel;
    private javax.swing.JTextField conditionTextField;
    private javax.swing.JLabel disLabel;
    private javax.swing.JTextField disTextField;
    private com.toedter.calendar.JDateChooser endDateChooser;
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private com.toedter.calendar.JDateChooser startDateChooser;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JPanel temp1Panel;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTextField;
    // End of variables declaration//GEN-END:variables
}
