
package View;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import model.MonAn;


public class itemPanel extends javax.swing.JPanel {
    
    private addItemListener addItemListener;
    private MonAn monAn;
    
    public void setAddItemListener(addItemListener listener) {
        this.addItemListener = listener;
    }

    public itemPanel() {
        initComponents();
        
        this.setPreferredSize(new Dimension(150, 250));
    }
    
    public void setMonAn(MonAn mon) {
        this.monAn = mon;
        setData(mon);
    }
        
    public void setData(MonAn mon) {
        setNameLabel(mon.getTenMon());
        setPriceLabel(mon.getGiaBan());
        setImage(mon.getImageIcon());
    }
    
    public void setNameLabel(String name) {
        String htmlText = "<html><div style='width:100px; text-align: center;'>" + name + "</div></html>";
        nameLabel.setText(htmlText);
    }


    public void setPriceLabel(double price) {
        priceLabel.setText(String.format("%.0f VNĐ", price));
    }

    public void setImage(ImageIcon icon) {
        if (icon != null) {
            Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            picLabel.setIcon(new ImageIcon(img));
            picLabel.setText("");
        } else {
            picLabel.setText("No Image");
        }
    }
        
    public void setImage(String imagePath) {
        try {
            ImageIcon icon = new ImageIcon(imagePath);
            Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            picLabel.setIcon(new ImageIcon(img));
            picLabel.setText(""); // xóa text placeholder "hinh"
        } catch (Exception e) {
            System.err.println("Không thể tải ảnh: " + imagePath);
            picLabel.setText("No Image");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemLabel = new javax.swing.JPanel();
        picLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        addButton = new javax.swing.JButton();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();

        itemLabel.setBackground(new java.awt.Color(255, 255, 255));

        picLabel.setText("hinh");
        picLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        picLabel.setPreferredSize(new java.awt.Dimension(120, 120));

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price");

        addButton.setBackground(new java.awt.Color(0, 191, 255));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        namePanel.setBackground(new java.awt.Color(255, 255, 255));
        namePanel.setLayout(null);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");
        namePanel.add(nameLabel);
        nameLabel.setBounds(10, 0, 130, 50);

        javax.swing.GroupLayout itemLabelLayout = new javax.swing.GroupLayout(itemLabel);
        itemLabel.setLayout(itemLabelLayout);
        itemLabelLayout.setHorizontalGroup(
            itemLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLabelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemLabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemLabelLayout.createSequentialGroup()
                        .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        itemLabelLayout.setVerticalGroup(
            itemLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLabelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(picLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantitySpinner)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (addItemListener != null && monAn != null) {
            int quantity = (int) quantitySpinner.getValue();
            if (quantity > 0) {
                addItemListener.onAddItem(monAn, quantity);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel itemLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel picLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSpinner quantitySpinner;
    // End of variables declaration//GEN-END:variables
}
