
package View;

import controller.NhanVienController;
import dao.NhanVienDAO;
import dao.TaiKhoanDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;

/**
 *
 * @author nttma
 */
public class M_employeePanel extends javax.swing.JPanel {

    public void loadAll() {
        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();
        model.setRowCount(0); 

        NhanVienDAO nvDAO = new NhanVienDAO();
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        List<NhanVien> list = nvDAO.findAll();         
        for (NhanVien nv : list) {
            String email = tkDAO.getEmailByMatk(nv.getMatk());

            String ngaysinhStr = nv.getNgaysinh() != null ? sdf.format(nv.getNgaysinh()) : null;
            String ngayvlStr = nv.getNgayvl() != null ? sdf.format(nv.getNgayvl()) : null;


            model.addRow(new Object[] {
                nv.getManv(),
                nv.getHoten(),
                ngaysinhStr,
                nv.getSdt(),
                email,
                ngayvlStr,
                nv.getChucvu(),
                String.format("%,.0f", nv.getLuong()),
                nv.getMaql(),
                nv.getMatk()
            });
        }
    }
    
    public NhanVien getSelectedNhanVien() {
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow == -1) return null;

        DefaultTableModel model = (DefaultTableModel) employeeTable.getModel();

        String manv = (String) model.getValueAt(selectedRow, 0);
        String hoten = (String) model.getValueAt(selectedRow, 1);

        Date ngaysinh = null;
        Date ngayvl = null;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        try {
            String ngaysinhStr = (String) model.getValueAt(selectedRow, 2);
            if (ngaysinhStr != null && !ngaysinhStr.trim().isEmpty()) {
                ngaysinh = sdf.parse(ngaysinhStr);
            }

            String ngayvlStr = (String) model.getValueAt(selectedRow, 5);
            if (ngayvlStr != null && !ngayvlStr.trim().isEmpty()) {
                ngayvl = sdf.parse(ngayvlStr);
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }

        String sdt = (String) model.getValueAt(selectedRow, 3);
        String email = (String) model.getValueAt(selectedRow, 4); 
        String chucvu = (String) model.getValueAt(selectedRow, 6);

        double luong = 0;
        Object luongObj = model.getValueAt(selectedRow, 7);
        if (luongObj != null) {
            String luongStr = luongObj.toString().replace(".", "").replace(",", ".");
            try {
                luong = Double.parseDouble(luongStr);
            } catch (NumberFormatException e) {
                luong = 0;
            }
        }

        String maql = (String) model.getValueAt(selectedRow, 8);
        String matk = (String) model.getValueAt(selectedRow, 9);

        return new NhanVien(manv, hoten, ngaysinh, sdt, ngayvl, chucvu, luong, maql, matk);
    }

    /**
     * Creates new form M_employeePanel
     */
    public M_employeePanel() {
        initComponents();
        
        insertButton.setContentAreaFilled(false);
        insertButton.setBorderPainted(false);
        insertButton.setFocusPainted(false);
        
        updateButton.setContentAreaFilled(false);
        updateButton.setBorderPainted(false);
        updateButton.setFocusPainted(false);
        
        deleteButton.setContentAreaFilled(false);
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        
        detailButton.setContentAreaFilled(false);
        detailButton.setBorderPainted(false);
        detailButton.setFocusPainted(false);
        
        loadAll();
        
        TableSearchUtil.enableSearch(employeeTable, searchTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        voucherScrollPane = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        search1Panel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        search2Panel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        voucherLabel = new javax.swing.JLabel();
        action1Panel = new javax.swing.JPanel();
        actionLabel1 = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(800, 750));
        tempPanel.setLayout(null);

        employeeTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Birth", "Phone number", "Email", "Start Date", "Position", "Salary", "Manager ID", "Account ID"
            }
        ));
        employeeTable.setRowHeight(30);
        voucherScrollPane.setViewportView(employeeTable);

        tempPanel.add(voucherScrollPane);
        voucherScrollPane.setBounds(10, 142, 780, 600);

        search1Panel.setBackground(new java.awt.Color(252, 252, 246));

        searchLabel.setBackground(new java.awt.Color(252, 252, 246));
        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        javax.swing.GroupLayout search1PanelLayout = new javax.swing.GroupLayout(search1Panel);
        search1Panel.setLayout(search1PanelLayout);
        search1PanelLayout.setHorizontalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        search1PanelLayout.setVerticalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search1PanelLayout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(search1Panel);
        search1Panel.setBounds(40, 50, 60, 20);

        search2Panel.setBackground(new java.awt.Color(252, 252, 246));
        search2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search2PanelLayout = new javax.swing.GroupLayout(search2Panel);
        search2Panel.setLayout(search2PanelLayout);
        search2PanelLayout.setHorizontalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        search2PanelLayout.setVerticalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tempPanel.add(search2Panel);
        search2Panel.setBounds(20, 60, 520, 60);

        voucherLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        voucherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        voucherLabel.setText("employee Management");
        tempPanel.add(voucherLabel);
        voucherLabel.setBounds(0, 10, 800, 33);

        action1Panel.setBackground(new java.awt.Color(252, 252, 246));

        actionLabel1.setBackground(new java.awt.Color(252, 252, 246));
        actionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actionLabel1.setText("Action");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action1PanelLayout.createSequentialGroup()
                .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(action1Panel);
        action1Panel.setBounds(590, 50, 60, 20);

        action2Panel.setBackground(new java.awt.Color(252, 252, 246));
        action2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add_30.png"))); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/update30.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/delete30.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        detailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/detail30.png"))); // NOI18N
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        tempPanel.add(action2Panel);
        action2Panel.setBounds(570, 60, 210, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        M_employee_insert employeeFrame = new M_employee_insert(this);
        employeeFrame.setVisible(true);
        employeeFrame.pack();
        employeeFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        NhanVien selected = getSelectedNhanVien();
        if (selected != null) {
            M_employee_update updateFrame = new M_employee_update(selected, this); 
            updateFrame.setVisible(true);
            updateFrame.pack();
            updateFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân viên để cập nhật.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        int row = employeeTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân viên để xem chi tiết.");
            return;
        }

        String manv = employeeTable.getValueAt(row, 0).toString();
        NhanVien nv = new NhanVienDAO().findById(manv);

        if (nv != null) {
            M_employee_detail detailFrame = new M_employee_detail(nv); 
            detailFrame.setVisible(true);
            detailFrame.pack();
            detailFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên.");
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = employeeTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một nhân viên để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String manv = employeeTable.getValueAt(selectedRow, 0).toString(); 

        NhanVienController controller = new NhanVienController(this, this);
        controller.handleDelete(manv, this::loadAll);
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JLabel actionLabel1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JTable employeeTable;
    private javax.swing.JButton insertButton;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel search1Panel;
    private javax.swing.JPanel search2Panel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JScrollPane voucherScrollPane;
    // End of variables declaration//GEN-END:variables
}
