
package View;

import controller.ChamCongController;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;
import model.ChamCong;

/**
 *
 * @author nttma
 */
public class M_home_T_detail extends javax.swing.JFrame {

    private M_home_T parent;
    private ChamCong chamCong;
    private ChamCongController chamCongController;

    
    public M_home_T_detail(M_home_T parent) {
        initComponents();
        this.parent = parent;
        
        chamCongController = new ChamCongController(this, parent);
        
        addEvents();
    }
        
    public M_home_T_detail(ChamCong chamCong) {
        initComponents();
        this.chamCong = chamCong;
        
        this.chamCongController = new ChamCongController(this, parent);
        
        tk_idTextField.setText(chamCong.getMaChamCong()); 
        e_idTextField.setText(chamCong.getMaNV());        
        hoursTextField.setText(String.valueOf(chamCong.getSoGioLam())); 
        workdateDateChooser.setDate(chamCong.getNgayLV()); 
        
        String tenNV = chamCongController.getTenNVByMaNV(chamCong.getMaNV());
        nameTextField.setText(tenNV != null ? tenNV : "");

        tk_idTextField.setEditable(false);  
        e_idTextField.setEditable(false);   
        hoursTextField.setEditable(false);  
        workdateDateChooser.setEnabled(false);  
        nameTextField.setEditable(false); 
    }

    private void addEvents() {
        e_idTextField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusLost(FocusEvent e) {
                String maNV = e_idTextField.getText().trim();
                if (!maNV.isEmpty()) {
                    String tenNV = chamCongController.getTenNVByMaNV(maNV);
                    if (tenNV != null) {
                        nameTextField.setText(tenNV);
                    } else {
                        nameTextField.setText("");
                        JOptionPane.showMessageDialog(M_home_T_detail.this, "Không tìm thấy nhân viên với mã này.");
                    }
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        tk_idLabel = new javax.swing.JLabel();
        tk_idTextField = new javax.swing.JTextField();
        workdateLabel = new javax.swing.JLabel();
        e_idLabel = new javax.swing.JLabel();
        e_idTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        hoursLabel = new javax.swing.JLabel();
        hoursTextField = new javax.swing.JTextField();
        workdateDateChooser = new com.toedter.calendar.JDateChooser();
        temp1Panel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(1100, 750));

        infoLabel.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Timekeeping Entry");

        tk_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tk_idLabel.setText("Timekeeping ID:");

        tk_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tk_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        tk_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tk_idTextFieldActionPerformed(evt);
            }
        });

        workdateLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        workdateLabel.setText("Work date:");

        e_idLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        e_idLabel.setText("Employee ID:");

        e_idTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        e_idTextField.setForeground(new java.awt.Color(102, 102, 102));
        e_idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e_idTextFieldActionPerformed(evt);
            }
        });

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLabel.setText("Name:");

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(102, 102, 102));
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        hoursLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hoursLabel.setText("Working hours:");

        hoursTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hoursTextField.setForeground(new java.awt.Color(102, 102, 102));
        hoursTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursTextFieldActionPerformed(evt);
            }
        });

        workdateDateChooser.setForeground(new java.awt.Color(102, 102, 102));

        temp1Panel.setBackground(new java.awt.Color(252, 252, 246));

        cancelButton.setBackground(new java.awt.Color(173, 181, 189));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(33, 37, 41));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout temp1PanelLayout = new javax.swing.GroupLayout(temp1Panel);
        temp1Panel.setLayout(temp1PanelLayout);
        temp1PanelLayout.setHorizontalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temp1PanelLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        temp1PanelLayout.setVerticalGroup(
            temp1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temp1PanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout tempPanelLayout = new javax.swing.GroupLayout(tempPanel);
        tempPanel.setLayout(tempPanelLayout);
        tempPanelLayout.setHorizontalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addComponent(workdateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(workdateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(e_idLabel)
                            .addComponent(nameLabel)
                            .addComponent(hoursLabel)
                            .addComponent(tk_idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                            .addComponent(hoursTextField)
                            .addComponent(tk_idTextField)
                            .addComponent(e_idTextField))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(temp1Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tempPanelLayout.setVerticalGroup(
            tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tempPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tk_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tk_idLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(e_idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(e_idLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workdateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tempPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(workdateLabel)))
                .addGap(18, 18, 18)
                .addGroup(tempPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursLabel))
                .addGap(37, 37, 37)
                .addComponent(temp1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tk_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tk_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tk_idTextFieldActionPerformed

    private void e_idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e_idTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void hoursTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursTextFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        if (parent != null) {
            parent.setVisible(true); 
        }
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel e_idLabel;
    private javax.swing.JTextField e_idTextField;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JTextField hoursTextField;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel temp1Panel;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel tk_idLabel;
    private javax.swing.JTextField tk_idTextField;
    private com.toedter.calendar.JDateChooser workdateDateChooser;
    private javax.swing.JLabel workdateLabel;
    // End of variables declaration//GEN-END:variables
}
