
package View;

import controller.ChamCongController;
import dao.ChamCongDAO;
import dao.NhanVienDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChamCong;

/**
 *
 * @author nttma
 */
public class M_home_T extends javax.swing.JFrame {

    private final ChamCongDAO chamCongDAO = new ChamCongDAO();
    private final NhanVienDAO nhanVienDAO = new NhanVienDAO();

    
    public void loadAll() {
        List<ChamCong> list = chamCongDAO.findAll(); 

        DefaultTableModel model = (DefaultTableModel) timeTable.getModel();
        model.setRowCount(0); 

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        for (ChamCong cc : list) {
            String tenNV = nhanVienDAO.getTenNVByMaNV(cc.getMaNV());
            Object[] row = new Object[] {
                cc.getMaChamCong(),
                cc.getMaNV(),
                tenNV != null ? tenNV : "",           
                sdf.format(cc.getNgayLV()),
                cc.getSoGioLam()
            };
            model.addRow(row);
        }
    }
    
    public ChamCong getSelectedChamCong() {
        int selectedRow = timeTable.getSelectedRow();
        if (selectedRow == -1) return null;

        DefaultTableModel model = (DefaultTableModel) timeTable.getModel();

        String maChamCong = (String) model.getValueAt(selectedRow, 0);
        String maNV = (String) model.getValueAt(selectedRow, 1);

        Date ngayLV = null;
        try {
            String ngayLVStr = (String) model.getValueAt(selectedRow, 3);
            if (ngayLVStr != null && !ngayLVStr.trim().isEmpty()) {
                ngayLV = new SimpleDateFormat("dd/MM/yyyy").parse(ngayLVStr);
            }
        } catch (ParseException e) {
            e.printStackTrace();
        }

        double soGioLam = 0;
        Object gioObj = model.getValueAt(selectedRow, 4);
        if (gioObj != null) {
            soGioLam = Double.parseDouble(gioObj.toString());
        }

        return new ChamCong(maChamCong, ngayLV, soGioLam, maNV);
    }

    /**
     * Creates new form E_home_T
     */
    public M_home_T() {
        initComponents();
        
        loadAll();
        
        insertButton.setContentAreaFilled(false);
        insertButton.setBorderPainted(false);
        insertButton.setFocusPainted(false);
        
        updateButton.setContentAreaFilled(false);
        updateButton.setBorderPainted(false);
        updateButton.setFocusPainted(false);
        
        deleteButton.setContentAreaFilled(false);
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        
        detailButton.setContentAreaFilled(false);
        detailButton.setBorderPainted(false);
        detailButton.setFocusPainted(false);
        
        returnButton.setContentAreaFilled(false);
        returnButton.setBorderPainted(false);
        returnButton.setFocusPainted(false);
        
        TableSearchUtil.enableSearch(timeTable, searchTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempPanel = new javax.swing.JPanel();
        timeScrollPane = new javax.swing.JScrollPane();
        timeTable = new javax.swing.JTable();
        search1Panel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        search2Panel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();
        action1Panel = new javax.swing.JPanel();
        actionLabel1 = new javax.swing.JLabel();
        action2Panel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        insertButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        detailButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tempPanel.setBackground(new java.awt.Color(252, 252, 246));
        tempPanel.setPreferredSize(new java.awt.Dimension(800, 750));
        tempPanel.setLayout(null);

        timeTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        timeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Timekeeping ID", "Employee ID", "Name", "Work Date", "Working Hours"
            }
        ));
        timeTable.setRowHeight(30);
        timeScrollPane.setViewportView(timeTable);

        tempPanel.add(timeScrollPane);
        timeScrollPane.setBounds(10, 212, 780, 530);

        search1Panel.setBackground(new java.awt.Color(252, 252, 246));

        searchLabel.setBackground(new java.awt.Color(252, 252, 246));
        searchLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchLabel.setText("Search");

        javax.swing.GroupLayout search1PanelLayout = new javax.swing.GroupLayout(search1Panel);
        search1Panel.setLayout(search1PanelLayout);
        search1PanelLayout.setHorizontalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        search1PanelLayout.setVerticalGroup(
            search1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search1PanelLayout.createSequentialGroup()
                .addComponent(searchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(search1Panel);
        search1Panel.setBounds(40, 110, 60, 20);

        search2Panel.setBackground(new java.awt.Color(252, 252, 246));
        search2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        searchTextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchTextField.setForeground(new java.awt.Color(102, 102, 102));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search2PanelLayout = new javax.swing.GroupLayout(search2Panel);
        search2Panel.setLayout(search2PanelLayout);
        search2PanelLayout.setHorizontalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        search2PanelLayout.setVerticalGroup(
            search2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, search2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tempPanel.add(search2Panel);
        search2Panel.setBounds(20, 120, 520, 60);

        timeLabel.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("timekeeping");
        tempPanel.add(timeLabel);
        timeLabel.setBounds(0, 70, 800, 33);

        action1Panel.setBackground(new java.awt.Color(252, 252, 246));

        actionLabel1.setBackground(new java.awt.Color(252, 252, 246));
        actionLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        actionLabel1.setText("Action");

        javax.swing.GroupLayout action1PanelLayout = new javax.swing.GroupLayout(action1Panel);
        action1Panel.setLayout(action1PanelLayout);
        action1PanelLayout.setHorizontalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );
        action1PanelLayout.setVerticalGroup(
            action1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action1PanelLayout.createSequentialGroup()
                .addComponent(actionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tempPanel.add(action1Panel);
        action1Panel.setBounds(590, 110, 60, 20);

        action2Panel.setBackground(new java.awt.Color(252, 252, 246));
        action2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/add_30.png"))); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/update30.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/delete30.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        detailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/detail30.png"))); // NOI18N
        detailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout action2PanelLayout = new javax.swing.GroupLayout(action2Panel);
        action2Panel.setLayout(action2PanelLayout);
        action2PanelLayout.setHorizontalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(action2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        action2PanelLayout.setVerticalGroup(
            action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, action2PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(action2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );

        tempPanel.add(action2Panel);
        action2Panel.setBounds(570, 120, 210, 60);

        jPanel2.setBackground(new java.awt.Color(207, 178, 145));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        returnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/return20.png"))); // NOI18N
        returnButton.setFocusPainted(false);
        returnButton.setPreferredSize(new java.awt.Dimension(30, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        jPanel2.add(returnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tempPanel.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tempPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
        // TODO add your handling code here:
        ChamCong selected = getSelectedChamCong();
        if (selected != null) {
            M_home_T_detail detailFrame = new M_home_T_detail(selected);
            detailFrame.setVisible(true);
            detailFrame.pack();
            detailFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xem chi tiết.");
        }
    }//GEN-LAST:event_detailButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        ChamCong selected = getSelectedChamCong();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ChamCongController controller = new ChamCongController(this, this);
        controller.deleteChamCong(selected.getMaChamCong(), this::loadAll);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        ChamCong selected = getSelectedChamCong();
        if (selected != null) {
            M_home_T_update timekeepingFrame = new M_home_T_update(selected, this);
            timekeepingFrame.setVisible(true);
            timekeepingFrame.pack();
            timekeepingFrame.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để cập nhật.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        M_home_T_insert timekeepingFrame = new M_home_T_insert(this);
        timekeepingFrame.setVisible(true);
        timekeepingFrame.pack();
        timekeepingFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_insertButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        E_homePanel homePanel = new E_homePanel();
        homePanel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel action1Panel;
    private javax.swing.JPanel action2Panel;
    private javax.swing.JLabel actionLabel1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton detailButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton returnButton;
    private javax.swing.JPanel search1Panel;
    private javax.swing.JPanel search2Panel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JPanel tempPanel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JScrollPane timeScrollPane;
    private javax.swing.JTable timeTable;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
